const categories = ['早餐', '肉菜', '水产', '半成品','主食', '汤类', '调味料', '饮品', '甜点']

// Base URL for GitHub Media CDN (GitHub LFS) - for images
const IMG_BASE = 'https://media.githubusercontent.com/media/Anduin2017/HowToCook/master/dishes'

// Category-specific image paths
const IMG = {
  breakfast: `${IMG_BASE}/breakfast`,
  meat_dish: `${IMG_BASE}/meat_dish`,
  vegetable_dish: `${IMG_BASE}/vegetable_dish`,
  staple: `${IMG_BASE}/staple`,
  soup: `${IMG_BASE}/soup`,
  drink: `${IMG_BASE}/drink`,
  aquatic: `${IMG_BASE}/aquatic`,
  condiment: `${IMG_BASE}/condiment`,
  dessert: `${IMG_BASE}/dessert`,
  semi_finished: `${IMG_BASE}/semi-finished`
}

// Tutorial URL base - using raw.githubusercontent.com for markdown files
const R = 'https://raw.githubusercontent.com/Anduin2017/HowToCook/master/dishes'

const dishes = [
  { id: 101, name: '鸡蛋三明治', emoji: '🥪', price: 0, desc: '10分钟简易三明治，营养方便，快手早餐首选', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg1.png`, tutorialUrl: `${R}/breakfast/鸡蛋三明治.md` },
  { id: 102, name: '牛奶燕麦', emoji: '🥣', price: 0, desc: '高蛋白粗谷物纤维，饱腹感强的懒人快速早餐', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg2.png`, tutorialUrl: `${R}/breakfast/牛奶燕麦.md` },
  { id: 103, name: '完美水煮蛋', emoji: '🥚', price: 0, desc: '蛋白嫩滑蛋黄恰到好处，完美火候的水煮蛋', category: '早餐', image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1yBdnK.img?w=400&h=300&m=6', tutorialUrl: `${R}/breakfast/完美水煮蛋.md` },
  { id: 104, name: '太阳蛋', emoji: '🍳', price: 0, desc: '简单快手，蛋黄嫩流，最经典的煎蛋早餐', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg3.png`, tutorialUrl: `${R}/breakfast/太阳蛋.md` },
  { id: 105, name: '吐司果酱', emoji: '🍞', price: 0, desc: '2分钟搞定，饱腹感强的懒人快速营养早餐', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg1.png`, tutorialUrl: `${R}/breakfast/吐司果酱.md` },
  { id: 106, name: '燕麦鸡蛋饼', emoji: '🧇', price: 0, desc: '极具营养，便于制作，适宜快速早餐的健康煎饼', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg2.png`, tutorialUrl: `${R}/breakfast/燕麦鸡蛋饼.md` },
  { id: 107, name: '蒸水蛋', emoji: '🥚', price: 0, desc: '嫩如豆腐脑，简单易做的家常蒸蛋', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg3.png`, tutorialUrl: `${R}/breakfast/蒸水蛋.md` },
  { id: 108, name: '茶叶蛋', emoji: '🥚', price: 0, desc: '茶香浓郁，鲜香可口的高蛋白快速营养早餐', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg1.png`, tutorialUrl: `${R}/breakfast/茶叶蛋.md` },
  { id: 109, name: '溏心蛋', emoji: '🥚', price: 0, desc: '蛋白嫩弹蛋黄半流，健身人士必备高蛋白早餐', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg2.png`, tutorialUrl: `${R}/breakfast/溏心蛋.md` },
  { id: 110, name: '金枪鱼酱三明治', emoji: '🥪', price: 0, desc: '饱腹感强的懒人早餐，高蛋白营养丰富', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg3.png`, tutorialUrl: `${R}/breakfast/金枪鱼酱三明治.md` },
  { id: 111, name: '手抓饼', emoji: '🫓', price: 0, desc: '外酥里嫩层次分明，街头经典早餐小吃', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg1.png`, tutorialUrl: `${R}/breakfast/手抓饼.md` },
  { id: 112, name: '煎饺', emoji: '🥟', price: 0, desc: '底部金黄酥脆，馅料鲜美多汁的早餐煎饺', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg2.png`, tutorialUrl: `${R}/breakfast/煎饺.md` },
  { id: 113, name: '韩国麻药鸡蛋', emoji: '🥚', price: 0, desc: '让人上瘾的韩式酱油浸蛋，简单好上手', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg3.png`, tutorialUrl: `${R}/breakfast/韩国麻药鸡蛋.md` },
  { id: 114, name: '意式香肠北非蛋', emoji: '🍳', price: 0, desc: '充满地中海风情的经典早午餐，简单大气', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg1.png`, tutorialUrl: `${R}/breakfast/意式香肠北非蛋.md` },
  { id: 115, name: '蒸花卷', emoji: '🥐', price: 0, desc: '松软暄腾，补充碳水化合物的传统中式早点', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg2.png`, tutorialUrl: `${R}/breakfast/蒸花卷.md` },
  { id: 116, name: '桂圆红枣粥', emoji: '🍚', price: 0, desc: '补血安神、健脑益智，甜口养生粥', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg3.png`, tutorialUrl: `${R}/breakfast/桂圆红枣粥.md` },
  { id: 117, name: '微波炉蒸蛋', emoji: '🥚', price: 0, desc: '嫩滑细腻快速上桌，微波炉搞定的高蛋白早餐', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg1.png`, tutorialUrl: `${R}/breakfast/微波炉蒸蛋.md` },
  
  // ======= 早餐（续）=======
  { id: 118, name: '微波炉荷包蛋', emoji: '🥚', price: 0, desc: '120秒快速完成，简单易做的高蛋白通勤早餐', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg2.png`, tutorialUrl: `${R}/breakfast/微波炉荷包蛋.md` },
  { id: 119, name: '微波炉蛋糕', emoji: '🍰', price: 0, desc: '2分钟"叮"出来的蛋糕，懒人烘焙甜点', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg3.png`, tutorialUrl: `${R}/breakfast/微波炉蛋糕.md` },
  { id: 120, name: '水煮玉米', emoji: '🌽', price: 0, desc: '15分钟完成，清甜爽脆的营养早点', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg1.png`, tutorialUrl: `${R}/breakfast/水煮玉米.md` },
  { id: 121, name: '空气炸锅面包片', emoji: '🍞', price: 0, desc: '健康饱肚子，正在减脂期的程序员必选', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg2.png`, tutorialUrl: `${R}/breakfast/空气炸锅面包片.md` },
  { id: 122, name: '美式炒蛋', emoji: '🍳', price: 0, desc: '松软鲜嫩口感，加牛奶更细密，营养丰富', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg3.png`, tutorialUrl: `${R}/breakfast/美式炒蛋.md` },
  { id: 123, name: '蛋煎糍粑', emoji: '🥟', price: 0, desc: '热量高美味顶饿便宜，十分钟快手早餐', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg1.png`, tutorialUrl: `${R}/breakfast/蛋煎糍粑.md` },
  { id: 124, name: '温泉蛋', emoji: '🥚', price: 0, desc: '传统日式小吃，蛋白不熟蛋黄熟的独特口感', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg2.png`, tutorialUrl: `${R}/breakfast/温泉蛋/温泉蛋.md` },
  { id: 125, name: '苏格兰蛋', emoji: '🥚', price: 0, desc: '蛋包肉末外酥里嫩，英式经典早点', category: '早餐', image: `${IMG.breakfast}/苏格兰蛋/egg1.png`, tutorialUrl: `${R}/breakfast/苏格兰蛋/苏格兰蛋.md` },
  
  { id:   1, name: '宫保鸡丁', emoji: '🍗', price: 0, desc: '老派川菜，鸡肉鲜嫩，花生酥脆，香辣可口', category: '肉菜', image: `${IMG.meat_dish}/宫保鸡丁/宫保鸡丁.jpg`, tutorialUrl: `${R}/meat_dish/宫保鸡丁/宫保鸡丁.md` },
  { id:   2, name: '麻婆豆腐', emoji: '🌶️', price: 0, desc: '麻辣鲜香，豆腐嫩滑入味，下饭神器', category: '肉菜', image: `${IMG.meat_dish}/麻婆豆腐/1.jpeg`, tutorialUrl: `${R}/meat_dish/麻婆豆腐/麻婆豆腐.md` },
  { id:   3, name: '红烧肉', emoji: '🥩', price: 0, desc: '新手不败菜谱，肥而不腻，色泽红亮入口即化', category: '肉菜', image: `${IMG.meat_dish}/红烧肉/000.jpg`, tutorialUrl: `${R}/meat_dish/红烧肉/简易红烧肉.md` },
  { id:   4, name: '糖醋排骨', emoji: '🍖', price: 0, desc: '外酥里嫩，酸甜适口，老少皆宜的经典名菜', category: '肉菜', image: `${IMG.meat_dish}/糖醋排骨/1.jpeg`, tutorialUrl: `${R}/meat_dish/糖醋排骨/糖醋排骨.md` },
  { id:   5, name: '回锅肉', emoji: '🥘', price: 0, desc: '经典川味，肉片肥瘦相间，配蒜苗更香', category: '肉菜', image: `${IMG.meat_dish}/回锅肉/1.jpeg`, tutorialUrl: `${R}/meat_dish/回锅肉/回锅肉.md` },
  { id:   6, name: '可乐鸡翅', emoji: '🍗', price: 0, desc: '可乐赋予鸡翅焦糖色泽，鲜香微甜超下饭', category: '肉菜', image: `${IMG.meat_dish}/农家一碗香/农家一碗香成品.jpg`, tutorialUrl: `${R}/meat_dish/可乐鸡翅/可乐鸡翅.md` },
  { id:   7, name: '红烧鸡翅', emoji: '🍗', price: 0, desc: '咸鲜带甜，色泽红亮，家常下饭必备', category: '肉菜', image: `${IMG.meat_dish}/香煎五花肉/香煎五花肉.jpg`, tutorialUrl: `${R}/meat_dish/红烧鸡翅/红烧鸡翅.md` },
  { id:   8, name: '鱼香肉丝', emoji: '🥩', price: 0, desc: '经典川菜，酸甜辣咸鲜五味俱全', category: '肉菜', image: `${IMG.meat_dish}/小炒黄牛肉/小炒黄牛肉.jpg`, tutorialUrl: `${R}/meat_dish/鱼香肉丝/鱼香肉丝.md` },
  { id:   9, name: '辣椒炒肉', emoji: '🌶️', price: 0, desc: '湖南经典家常菜，辣香四溢，超级下饭', category: '肉菜', image: `${IMG.meat_dish}/黑椒牛柳/黑椒牛柳.jpg`, tutorialUrl: `${R}/meat_dish/辣椒炒肉/辣椒炒肉.md` },
  { id:  10, name: '黄焖鸡', emoji: '🍗', price: 0, desc: '十分下饭，食材平平无奇却味道惊艳', category: '肉菜', image: `${IMG.meat_dish}/香菇滑鸡/香菇滑鸡.jpg`, tutorialUrl: `${R}/meat_dish/黄焖鸡/黄焖鸡.md` },
  { id:  11, name: '梅菜扣肉', emoji: '🥩', price: 0, desc: '造型别致，颜色酱红油亮，肥而不腻', category: '肉菜', image: `${IMG.meat_dish}/梅菜扣肉/1.jpeg`, tutorialUrl: `${R}/meat_dish/梅菜扣肉/梅菜扣肉.md` },
  { id:  12, name: '蚂蚁上树', emoji: '🍜', price: 0, desc: '经典川菜，粉丝吸汁，鲜辣入味', category: '肉菜', image: `${IMG.meat_dish}/咖喱肥牛/咖喱肥牛.jpg`, tutorialUrl: `${R}/meat_dish/蚂蚁上树/蚂蚁上树.md` },
  { id:  13, name: '西红柿牛腩', emoji: '🍅', price: 0, desc: '汤汁浓厚酸甜可口，牛肉软绵醇香', category: '肉菜', image: `${IMG.meat_dish}/湘祁米夫鸭/湘祁米夫鸭.jpg`, tutorialUrl: `${R}/meat_dish/西红柿牛腩/西红柿牛腩.md` },
  { id:  14, name: '香菇滑鸡', emoji: '🍄', price: 0, desc: '鲜香菇配嫩鸡，简单易做，鲜味十足', category: '肉菜', image: `${IMG.meat_dish}/香菇滑鸡/香菇滑鸡.jpg`, tutorialUrl: `${R}/meat_dish/香菇滑鸡/香菇滑鸡.md` },
  { id:  15, name: '水煮肉片', emoji: '🥩', price: 0, desc: '麻辣鲜香，适合干饭，川味经典名菜', category: '肉菜', image: `${IMG.meat_dish}/湖南家常红烧肉/湖南家常红烧肉.jpeg`, tutorialUrl: `${R}/meat_dish/水煮肉片/水煮肉片.md` },
  { id:  16, name: '黑椒牛柳', emoji: '🥩', price: 0, desc: '黑椒香浓，牛柳嫩滑，西式与中式完美结合', category: '肉菜', image: `${IMG.meat_dish}/黑椒牛柳/黑椒牛柳.jpg`, tutorialUrl: `${R}/meat_dish/黑椒牛柳/黑椒牛柳.md` },

  // ======= 肉菜 (续) =======
  { id:  17, name: '乡村啤酒鸭', emoji: '🦆', price: 0, desc: '将鸭肉与啤酒一同炖煮成菜，使滋补的鸭肉味道更加浓厚，鸭肉不仅入口鲜香，还带有一股啤酒清香。一般初学者只需要 1 小时即可', category: '肉菜', image: `${IMG.meat_dish}/乡村啤酒鸭/乡村啤酒鸭.jpg`, tutorialUrl: `${R}/meat_dish/乡村啤酒鸭/乡村啤酒鸭.md` },
  { id:  18, name: '农家一碗香', emoji: '🍖', price: 0, desc: '农家一碗香，是一道地道的湖南菜，里面主要食材有青椒、鸡蛋和猪肉。味道咸香下饭，而且这道菜烹饪简单，不需要特别的处理。', category: '肉菜', image: `${IMG.meat_dish}/农家一碗香/农家一碗香成品.jpg`, tutorialUrl: `${R}/meat_dish/农家一碗香/农家一碗香.md` },
  { id:  19, name: '冬瓜酿肉', emoji: '🥘', price: 0, desc: '荤素搭配，鲜嫩爽滑,做法简单。一般 30 分钟。', category: '肉菜', image: `${IMG.meat_dish}/冬瓜酿肉/冬瓜酿肉成品.jpg`, tutorialUrl: `${R}/meat_dish/冬瓜酿肉/冬瓜酿肉.md` },
  { id:  20, name: '冷吃兔', emoji: '🐰', price: 0, desc: '- 小葱/大葱/洋葱', category: '肉菜', image: `${IMG.meat_dish}/冷吃兔/冷吃兔.jpg`, tutorialUrl: `${R}/meat_dish/冷吃兔/冷吃兔.md` },
  { id:  21, name: '凉拌鸡丝', emoji: '🍗', price: 0, desc: '隔离期间的一道快手菜，少油低卡，制作简单，预计制作时间 30 分钟', category: '肉菜', image: `${IMG.meat_dish}/凉拌鸡丝/凉拌鸡丝_撕.jpg`, tutorialUrl: `${R}/meat_dish/凉拌鸡丝/凉拌鸡丝.md` },
  { id:  22, name: '卤菜', emoji: '🍖', price: 0, desc: '卤菜是一道经典的中式卤味料理，富含蛋白质和多种维生素。肉质鲜嫩多汁，香气四溢，入味程度可根据浸泡时间自行调整。这道菜适合', category: '肉菜', image: `${IMG.meat_dish}/卤菜/卤水.jpeg`, tutorialUrl: `${R}/meat_dish/卤菜/卤菜.md` },
  { id:  23, name: '口水鸡', emoji: '🍗', price: 0, desc: '口水鸡（凉菜），炎炎夏日里，热菜难以入口，但又嗜肉如命，', category: '肉菜', image: `${IMG.meat_dish}/口水鸡/口水鸡.jpg`, tutorialUrl: `${R}/meat_dish/口水鸡/口水鸡.md` },
  { id:  24, name: '台式卤肉饭', emoji: '🥘', price: 0, desc: '糖和脂肪是人类快乐的源泉，富含这二者的台式卤肉饭每一口都能带来直击灵魂的满足感。', category: '肉菜', image: `${IMG.meat_dish}/台式卤肉饭/1.jpg`, tutorialUrl: `${R}/meat_dish/台式卤肉饭/台式卤肉饭.md` },
  { id:  25, name: '咕噜肉', emoji: '🥘', price: 0, desc: '咕噜肉是非常下饭的菜肴，只需一道就可以吃得津津有味，大人小孩都爱吃。而这次做的是简易版菠萝咕噜肉，利用简单的材料就可以在', category: '肉菜', image: `${IMG.meat_dish}/咕噜肉/咕噜肉.jpg`, tutorialUrl: `${R}/meat_dish/咕噜肉/咕噜肉.md` },
  { id:  26, name: '咖喱肥牛', emoji: '🥩', price: 0, desc: '咖喱肥牛美味营养并且下饭，吃多了炒炸菜后再吃个咖喱肥牛相当美滋滋。', category: '肉菜', image: `${IMG.meat_dish}/咖喱肥牛/咖喱肥牛.jpg`, tutorialUrl: `${R}/meat_dish/咖喱肥牛/咖喱肥牛.md` },
  { id:  27, name: '商芝肉', emoji: '🥘', price: 0, desc: '此菜色泽红润，质地软嫩，肥而不腻，有浓郁的商芝香味，是陕西省商县特有的风味菜。因商芝属于陕西特产，此菜原料获取难度较大，', category: '肉菜', image: `${IMG.meat_dish}/商芝肉/商芝肉.jpg`, tutorialUrl: `${R}/meat_dish/商芝肉/商芝肉.md` },
  { id:  28, name: '啤酒鸭', emoji: '🦆', price: 0, desc: '啤酒鸭不仅入口鲜香,还带有一股啤酒清香。肉久吃不腻,汤久涮而不淡。风味独特,具有热而不浮,香而不腻的独特口味让人赞口不绝', category: '肉菜', image: `${IMG.meat_dish}/啤酒鸭/啤酒鸭.jpg`, tutorialUrl: `${R}/meat_dish/啤酒鸭/啤酒鸭.md` },
  { id:  29, name: '土豆炖排骨', emoji: '🍖', price: 0, desc: '注意：以下参数为标准 2-3 人份的精确配置。', category: '肉菜', image: `${IMG.meat_dish}/土豆炖排骨/排骨1.jpg`, tutorialUrl: `${R}/meat_dish/土豆炖排骨/土豆炖排骨.md` },
  { id:  30, name: '奶酪培根通心粉', emoji: '🍖', price: 0, desc: '这是一道美味的奶酪培根通心粉(Mac and Cheese)，适合四人享用。它结合了浓郁的奶酪和香脆的培根，简单易做，是', category: '肉菜', image: `${IMG.meat_dish}/奶酪培根通心粉/onepot.png`, tutorialUrl: `${R}/meat_dish/奶酪培根通心粉/奶酪培根通心粉.md` },
  { id:  31, name: '姜炒鸡', emoji: '🍗', price: 0, desc: '姜炒鸡是一道湖南口味菜，下饭五颗星，食材平平无奇又十分容易烹制，一学就会。', category: '肉菜', image: `${IMG.meat_dish}/姜炒鸡/姜炒鸡.jpg`, tutorialUrl: `${R}/meat_dish/姜炒鸡/姜炒鸡.md` },
  { id:  32, name: '姜葱捞鸡', emoji: '🍗', price: 0, desc: '嫩滑爆汁，白饭杀手，简单易做，', category: '肉菜', image: `${IMG.meat_dish}/姜葱捞鸡/姜葱捞鸡.jpg`, tutorialUrl: `${R}/meat_dish/姜葱捞鸡/姜葱捞鸡.md` },
  { id:  33, name: '孜然牛肉', emoji: '🥩', price: 0, desc: '* 牛柳或牛肩肉', category: '肉菜', image: `${IMG.meat_dish}/孜然牛肉/孜然牛肉.jpg`, tutorialUrl: `${R}/meat_dish/孜然牛肉/孜然牛肉.md` },
  { id:  34, name: '小炒肉', emoji: '🥘', price: 0, desc: '- 五花肉 500g', category: '肉菜', image: `${IMG.meat_dish}/小炒肉/小炒肉.jpg`, tutorialUrl: `${R}/meat_dish/小炒肉/小炒肉.md` },
  { id:  35, name: '小炒鸡肝', emoji: '🍗', price: 0, desc: '一道稍微麻烦的菜。', category: '肉菜', image: `${IMG.meat_dish}/小炒鸡肝/成品.jpg`, tutorialUrl: `${R}/meat_dish/小炒鸡肝/小炒鸡肝.md` },
  { id:  36, name: '小炒黄牛肉', emoji: '🥩', price: 0, desc: '小炒黄牛肉是一道简单易做的湘菜。口味十分劲爆爽口。一般初学者只需要 1 小时即可完成', category: '肉菜', image: `${IMG.meat_dish}/小炒黄牛肉/小炒黄牛肉.jpg`, tutorialUrl: `${R}/meat_dish/小炒黄牛肉/小炒黄牛肉.md` },
  { id:  37, name: '小米辣炒肉', emoji: '🥘', price: 0, desc: '* 五花肉/瘦肉', category: '肉菜', image: `${IMG.meat_dish}/小米辣炒肉/小米辣炒肉.jpg`, tutorialUrl: `${R}/meat_dish/小米辣炒肉/小米辣炒肉.md` },
  { id:  38, name: '小酥肉', emoji: '🥘', price: 0, desc: '- 去皮猪肉（根据喜好选择肥瘦）', category: '肉菜', image: `${IMG.meat_dish}/小酥肉/小酥肉.jpg`, tutorialUrl: `${R}/meat_dish/小酥肉/小酥肉.md` },
  { id:  39, name: '尖叫牛蛙', emoji: '🥩', price: 0, desc: '尖叫牛蛙是一道容易完成的菜。一般初学者只需要 1-2 小时即可完成。该菜品味道鲜美之外，还具有开胃功效，非常适宜食欲不佳', category: '肉菜', image: `${IMG.meat_dish}/尖叫牛蛙/尖叫牛蛙.jpg`, tutorialUrl: `${R}/meat_dish/尖叫牛蛙/尖叫牛蛙.md` },
  { id:  40, name: '尖椒炒牛肉', emoji: '🥩', price: 0, desc: '* 葱、姜、蒜', category: '肉菜', image: `${IMG.meat_dish}/尖椒炒牛肉/尖椒炒牛肉.jpg`, tutorialUrl: `${R}/meat_dish/尖椒炒牛肉/尖椒炒牛肉.md` },
  { id:  41, name: '山西过油肉', emoji: '🥘', price: 0, desc: '过油肉是山西传统名菜，有很多年历史，基本家家都会做。', category: '肉菜', image: `${IMG.meat_dish}/山西过油肉/山西过油肉.jpg`, tutorialUrl: `${R}/meat_dish/山西过油肉/山西过油肉.md` },
  { id:  42, name: '巴基斯坦牛肉咖喱', emoji: '🥩', price: 0, desc: 'Achar gosht（巴基斯坦牛肉咖喱）是一道来自巴基斯坦的特色咖喱菜品。这道菜融合了咖喱的香浓和牛肉的软糯口感，风味', category: '肉菜', image: `${IMG.meat_dish}/巴基斯坦牛肉咖喱/巴基斯坦牛肉咖喱.png`, tutorialUrl: `${R}/meat_dish/巴基斯坦牛肉咖喱/巴基斯坦牛肉咖喱.md` },
  { id:  43, name: '带把肘子', emoji: '🍖', price: 0, desc: '肘肉酥烂不腻，肘皮胶粘，香醇味美，辅佐以葱段，甜面酱，别有一番风味，因脚爪形似把柄，故得其名，是陕西省大荔县名菜。营养价', category: '肉菜', image: `${IMG.meat_dish}/带把肘子/带把肘子.jpg`, tutorialUrl: `${R}/meat_dish/带把肘子/带把肘子.md` },
  { id:  44, name: '干煸仔鸡', emoji: '🍗', price: 0, desc: '干煸仔鸡是一道甜辣口味的川菜，是北京大学食堂赵春月厨师长研发的美食，广受师生喜爱。赵厨师长已将菜谱公开，方便大家自己动手', category: '肉菜', image: `${IMG.meat_dish}/干煸仔鸡/干煸仔鸡成品.jpg`, tutorialUrl: `${R}/meat_dish/干煸仔鸡/干煸仔鸡.md` },
  { id:  45, name: '广式萝卜牛腩', emoji: '🥩', price: 0, desc: '广式萝卜牛腩营养丰富，味道鲜美，汤汁浓郁、孩子食欲好了，成绩也好了。', category: '肉菜', image: `${IMG.meat_dish}/广式萝卜牛腩/广式萝卜牛腩.webp`, tutorialUrl: `${R}/meat_dish/广式萝卜牛腩/广式萝卜牛腩.md` },
  { id:  46, name: '徽派红烧肉', emoji: '🥘', price: 0, desc: '徽式红烧肉是一道由五花肉等食材制成的菜肴。', category: '肉菜', image: `${IMG.meat_dish}/徽派红烧肉/1.jpeg`, tutorialUrl: `${R}/meat_dish/徽派红烧肉/徽派红烧肉.md` },
  { id:  47, name: '意式烤鸡', emoji: '🍗', price: 0, desc: '- 鸡腿肉用量通常来说为 1-2 个/人', category: '肉菜', image: `${IMG.meat_dish}/意式烤鸡/意式烤鸡.jpg`, tutorialUrl: `${R}/meat_dish/意式烤鸡/意式烤鸡.md` },
  { id:  48, name: '新疆大盘鸡', emoji: '🍗', price: 0, desc: '- 花椒，香叶，香果，干线椒，大蒜，大葱', category: '肉菜', image: `${IMG.meat_dish}/新疆大盘鸡/大盘鸡.jpeg`, tutorialUrl: `${R}/meat_dish/新疆大盘鸡/新疆大盘鸡.md` },
  { id:  49, name: '无骨鸡爪', emoji: '🍗', price: 0, desc: '**图片里的颜色比较浅，家里人爱吃酱油少的**', category: '肉菜', image: `${IMG.meat_dish}/无骨鸡爪/无骨鸡爪.jpg`, tutorialUrl: `${R}/meat_dish/无骨鸡爪/无骨鸡爪.md` },
  { id:  50, name: '杀猪菜', emoji: '🐷', price: 0, desc: '杀猪菜的做法 （荤菜）', category: '肉菜', image: `${IMG.meat_dish}/杀猪菜/杀猪菜.jpg`, tutorialUrl: `${R}/meat_dish/杀猪菜/杀猪菜.md` },
  { id:  51, name: '枝竹羊腩煲', emoji: '🐑', price: 0, desc: '枝竹羊腩煲是一份老少皆宜，适合冬季暖胃的美食。 此道菜肥而不腻，搭配米饭堪称一绝。一般初学者需 2 个半小时即可完成。', category: '肉菜', image: `${IMG.meat_dish}/枝竹羊腩煲/枝竹羊腩煲.jpg`, tutorialUrl: `${R}/meat_dish/枝竹羊腩煲/枝竹羊腩煲.md` },
  { id:  52, name: '柱候牛腩', emoji: '🥩', price: 0, desc: '肉香味美，色泽诱人，滋补强壮，口感甚佳，令人垂涎的广式菜肴。有高压锅只需 1 个小时，否则需要炖煮 3 个小时。', category: '肉菜', image: `${IMG.meat_dish}/柱候牛腩/柱候牛腩.jpeg`, tutorialUrl: `${R}/meat_dish/柱候牛腩/柱候牛腩.md` },
  { id:  53, name: '椒盐排条', emoji: '🍖', price: 0, desc: '椒盐排条是道非常经典的本帮菜，咸、香，也容易制作。', category: '肉菜', image: `${IMG.meat_dish}/椒盐排条/椒盐排条.jpg`, tutorialUrl: `${R}/meat_dish/椒盐排条/椒盐排条.md` },
  { id:  54, name: '水煮牛肉', emoji: '🥩', price: 0, desc: '- 干辣椒粉', category: '肉菜', image: `${IMG.meat_dish}/水煮牛肉/sznr1.jpg`, tutorialUrl: `${R}/meat_dish/水煮牛肉/水煮牛肉.md` },
  { id:  55, name: '洋葱炒猪肉', emoji: '🐷', price: 0, desc: '咸中带甜，简单上手，一不小心可能让人多吃一碗饭。一般只需 15 分钟即可完成。', category: '肉菜', image: `${IMG.meat_dish}/洋葱炒猪肉/洋葱炒猪肉.jpg`, tutorialUrl: `${R}/meat_dish/洋葱炒猪肉/洋葱炒猪肉.md` },
  { id:  56, name: '清蒸鳜鱼', emoji: '🐟', price: 0, desc: '鳜鱼可以称的上淡水鱼之王，味道鲜美，所谓高端的食材只需要最简单的烹饪方式，清蒸最能体现鳜鱼的鲜美。', category: '肉菜', image: `${IMG.meat_dish}/清蒸鳜鱼/清蒸鳜鱼成品图.jpg`, tutorialUrl: `${R}/meat_dish/清蒸鳜鱼/清蒸鳜鱼.md` },
  { id:  57, name: '湖南家常红烧肉', emoji: '🥘', price: 0, desc: '湖南家常红烧肉，入口软糯，肥而不腻', category: '肉菜', image: `${IMG.meat_dish}/湖南家常红烧肉/湖南家常红烧肉.jpeg`, tutorialUrl: `${R}/meat_dish/湖南家常红烧肉/湖南家常红烧肉.md` },
  { id:  58, name: '湘祁米夫鸭', emoji: '🦆', price: 0, desc: '湖南两祁地区特色菜品，逢年过节家家桌上有。鸭肉被米粉子包裹，入口咸香回味悠长可解乡愁。', category: '肉菜', image: `${IMG.meat_dish}/湘祁米夫鸭/湘祁米夫鸭.jpg`, tutorialUrl: `${R}/meat_dish/湘祁米夫鸭/湘祁米夫鸭.md` },
  { id:  59, name: '澳门湿版免治牛肉饭', emoji: '🥩', price: 0, desc: '这是一款适合一人食的快手神饭，嫩滑的牛肉碎裹着蛋液和浓郁的酱汁，混在米饭里每一口都咸香诱人。', category: '肉菜', image: `${IMG.meat_dish}/澳门湿版免治牛肉饭/澳门湿版免治牛肉饭.jpg`, tutorialUrl: `${R}/meat_dish/澳门湿版免治牛肉饭/澳门湿版免治牛肉饭.md` },
  { id:  60, name: '烤鸡翅', emoji: '🍗', price: 0, desc: '- 黑胡椒粉', category: '肉菜', image: `${IMG.meat_dish}/烤鸡翅/烤鸡翅.jpg`, tutorialUrl: `${R}/meat_dish/烤鸡翅/烤鸡翅.md` },
  { id:  61, name: '煎烤羊排', emoji: '🐑', price: 0, desc: '煎烤羊排是一道兼具炖煮与煎制工艺的菜品，外酥里嫩、香气四溢。既可作为家庭聚餐的硬菜，也能在宴会大餐中作为亮点端上桌。炖煮', category: '肉菜', image: `${IMG.meat_dish}/煎烤羊排/煎烤羊排.jpg`, tutorialUrl: `${R}/meat_dish/煎烤羊排/煎烤羊排.md` },
  { id:  62, name: '牛排', emoji: '🥩', price: 0, desc: '牛排是一种广受欢迎的西式肉类料理，富含蛋白质、油脂和铁、锌等矿物质。牛排的烹饪过程通过灵活的烹饪手法（如煎、烤、慢煮、熟', category: '肉菜', image: `${IMG.meat_dish}/牛排/牛排.jpg`, tutorialUrl: `${R}/meat_dish/牛排/牛排.md` },
  { id:  63, name: '猪皮冻', emoji: '🐷', price: 0, desc: '猪皮冻是一道简单易做的菜。北方人年夜饭餐桌上的“常青树”，晶莹剔透的外表，滑嫩 Q 弹的口感，是不折不扣的超级下酒菜。', category: '肉菜', image: `${IMG.meat_dish}/猪皮冻/猪皮冻.jpg`, tutorialUrl: `${R}/meat_dish/猪皮冻/猪皮冻.md` },
  { id:  64, name: '猪肉烩酸菜', emoji: '🐷', price: 0, desc: '猪肉烩酸菜是一道北方名菜，简单易做。富含蛋白质。一般初学者需要 3 小时完成。', category: '肉菜', image: `${IMG.meat_dish}/猪肉烩酸菜/猪肉烩酸菜.jpg`, tutorialUrl: `${R}/meat_dish/猪肉烩酸菜/猪肉烩酸菜.md` },
  { id:  65, name: '甜辣烤全翅', emoji: '🍖', price: 0, desc: '本甜辣烤全翅使用空气炸锅烹饪并仅使用家中常见调料，低油脂并且不需要成品烧烤酱，一份适合单人食用，食材处理需要 15 分钟', category: '肉菜', image: `${IMG.meat_dish}/甜辣烤全翅/甜辣烤全翅.jpg`, tutorialUrl: `${R}/meat_dish/甜辣烤全翅/甜辣烤全翅.md` },
  { id:  66, name: '番茄红酱', emoji: '🍖', price: 0, desc: '番茄红酱香浓可口，营养丰富，咱很喜欢。可以作为薄饼、意面~~热干面~~等主食的百搭酱料。有些繁琐，适合有烹饪经验的人尝试', category: '肉菜', image: `${IMG.meat_dish}/番茄红酱/番茄红酱.jpg`, tutorialUrl: `${R}/meat_dish/番茄红酱/番茄红酱.md` },
  { id:  67, name: '瘦肉土豆片', emoji: '🥘', price: 0, desc: '瘦肉土豆片是一道简单易做的菜。小炒家常菜，方便快速，适合上班族用于带饭必备小炒菜。一般初学者只需要 1 小时即可完成。', category: '肉菜', image: `${IMG.meat_dish}/瘦肉土豆片/瘦肉土豆片.jpg`, tutorialUrl: `${R}/meat_dish/瘦肉土豆片/瘦肉土豆片.md` },
  { id:  68, name: '白菜猪肉炖粉条', emoji: '🐷', price: 0, desc: '白菜猪肉炖粉条是一道简单易做的菜。这是一道传统的东北家常菜，以做法简单、味道上乘的特点，在广大东北人民群众中备受喜爱。', category: '肉菜', image: `${IMG.meat_dish}/白菜猪肉炖粉条/白菜猪肉炖粉条.jpg`, tutorialUrl: `${R}/meat_dish/白菜猪肉炖粉条/白菜猪肉炖粉条.md` },
  { id:  69, name: '粉蒸肉', emoji: '🥘', price: 0, desc: '粉蒸肉是一道经典的中式蒸菜，香味浓郁，口感软糯，营养丰富。适合家庭聚餐或节日宴客。此菜适合有一定烹饪经验的人士制作，预计', category: '肉菜', image: `${IMG.meat_dish}/粉蒸肉/粉蒸肉.jpg`, tutorialUrl: `${R}/meat_dish/粉蒸肉/粉蒸肉.md` },
  { id:  70, name: '糖醋里脊', emoji: '🍖', price: 0, desc: '糖醋里脊是中国经典传统名菜之一，该菜品以猪里脊肉为主材，配以面粉、淀粉、醋等佐料，酸甜可口，让人食欲大开；该菜品在陕菜、', category: '肉菜', image: `${IMG.meat_dish}/糖醋里脊/糖醋里脊.jpg`, tutorialUrl: `${R}/meat_dish/糖醋里脊/糖醋里脊.md` },
  { id:  71, name: '红烧猪蹄', emoji: '🐷', price: 0, desc: '红烧猪蹄营养丰富，味道香，汤汁浓郁、下饭强。', category: '肉菜', image: `${IMG.meat_dish}/红烧猪蹄/红烧猪蹄.jpg`, tutorialUrl: `${R}/meat_dish/红烧猪蹄/红烧猪蹄.md` },
  { id:  72, name: '羊排焖面', emoji: '🐑', price: 0, desc: '羊排焖面是一道硬菜，适合聚会时候大展身手。缺点就是有点花时间，优点就是好吃，而且一道菜补齐人体所需的三大营养物质。', category: '肉菜', image: `${IMG.meat_dish}/羊排焖面/羊排焖面.jpg`, tutorialUrl: `${R}/meat_dish/羊排焖面/羊排焖面.md` },
  { id:  73, name: '老妈蹄花', emoji: '🍖', price: 0, desc: '红烧猪蹄营养丰富，口感细腻，软烂脱骨，配上酸辣汁简直太香！', category: '肉菜', image: `${IMG.meat_dish}/老妈蹄花/result1.jpg`, tutorialUrl: `${R}/meat_dish/老妈蹄花/老妈蹄花.md` },
  { id:  74, name: '老式锅包肉', emoji: '🥘', price: 0, desc: '锅包肉是东北名菜，创始于光绪年间哈尔滨道台府厨师郑兴文之手。老式锅包肉的酸味来源于白醋汁，口味酸甜酥脆。', category: '肉菜', image: `${IMG.meat_dish}/老式锅包肉/老式锅包肉.jpg`, tutorialUrl: `${R}/meat_dish/老式锅包肉/老式锅包肉.md` },
  { id:  75, name: '肉饼炖蛋', emoji: '🥘', price: 0, desc: '肉饼炖蛋是一道传统的中国家常菜，也是一道非常受欢迎的下饭菜。初学者只需要 20 分钟即可完成。', category: '肉菜', image: `${IMG.meat_dish}/肉饼炖蛋/肉饼炖蛋.jpg`, tutorialUrl: `${R}/meat_dish/肉饼炖蛋/肉饼炖蛋.md` },
  { id:  76, name: '腐乳肉', emoji: '🥘', price: 0, desc: '腐乳肉精选五花肉与红腐乳缠绵共舞。腐乳特有的酒香豆香渗入肉纹，经慢火煨炖化作琥珀色的温柔。入口即化的肉质裹着微甜咸鲜的酱', category: '肉菜', image: `${IMG.meat_dish}/腐乳肉/腐乳肉.jpg`, tutorialUrl: `${R}/meat_dish/腐乳肉/腐乳肉.md` },
  { id:  77, name: '芥末罗氏虾', emoji: '🦐', price: 0, desc: '本菜品可替换成任意虾种类，包括但不限于基围虾、花虾、黑虎虾等。鲜香入味、芥末风味十足、吃完吮指，且操作十分简单。', category: '肉菜', image: `${IMG.meat_dish}/芥末罗氏虾/芥末罗氏虾成品.jpg`, tutorialUrl: `${R}/meat_dish/芥末罗氏虾/芥末罗氏虾.md` },
  { id:  78, name: '茭白炒肉', emoji: '🥘', price: 0, desc: '茭白味道鲜美，有一定营养价值', category: '肉菜', image: `${IMG.meat_dish}/茭白炒肉/1.jpeg`, tutorialUrl: `${R}/meat_dish/茭白炒肉/茭白炒肉.md` },
  { id:  79, name: '荔枝肉', emoji: '🥘', price: 0, desc: '荔枝肉独具闽菜特点，味道酸甜可口。是福州地区比较常见的一道菜肴', category: '肉菜', image: `${IMG.meat_dish}/荔枝肉/6.jpeg`, tutorialUrl: `${R}/meat_dish/荔枝肉/荔枝肉.md` },
  { id:  80, name: '荷兰豆炒腊肠', emoji: '🍖', price: 0, desc: '荷兰豆炒腊肠是一道营养丰富，口感清爽，有利于开胃助食，增进食欲的美味菜肴。荷兰豆中富含人体所需的各种营养物质，尤其是含有', category: '肉菜', image: `${IMG.meat_dish}/荷兰豆炒腊肠/2.png`, tutorialUrl: `${R}/meat_dish/荷兰豆炒腊肠/荷兰豆炒腊肠.md` },
  { id:  81, name: '萝卜炖羊排', emoji: '🐑', price: 0, desc: '萝卜炖羊排是一道常见家常菜，老少皆宜。一般初学者只需要最多 2 小时即可完成。', category: '肉菜', image: `${IMG.meat_dish}/萝卜炖羊排/萝卜炖羊排.jpg`, tutorialUrl: `${R}/meat_dish/萝卜炖羊排/萝卜炖羊排.md` },
  { id:  82, name: '蒜苔炒肉末', emoji: '🥘', price: 0, desc: '蒜苔炒肉末是一道简单易做的菜。这是一道北方家常菜，以做法简单、味道上乘的特点，在广大北方人民群众中备受喜爱。', category: '肉菜', image: `${IMG.meat_dish}/蒜苔炒肉末/蒜苔炒肉末.jpg`, tutorialUrl: `${R}/meat_dish/蒜苔炒肉末/蒜苔炒肉末.md` },
  { id:  83, name: '虎皮肘子', emoji: '🍖', price: 0, desc: '虎皮肘子是一道传统名菜，以猪肘为主料，通过先烧再炸后炖三个步骤使肘子皮呈现出虎皮状。肘子皮软烂入味，肥而不腻，瘦肉松软可', category: '肉菜', image: `${IMG.meat_dish}/虎皮肘子/虎皮肘子.jpg`, tutorialUrl: `${R}/meat_dish/虎皮肘子/虎皮肘子.md` },
  { id:  84, name: '血浆鸭', emoji: '🦆', price: 0, desc: '血浆鸭是湖南武冈特色传统名菜，香、脆可口，由于醋血的作用，不仅鸭骨酥而脆，就是姜和辣椒也变得不辣而甜净。一般初学者只需要', category: '肉菜', image: `${IMG.meat_dish}/血浆鸭/血浆鸭(特辣).jpg`, tutorialUrl: `${R}/meat_dish/血浆鸭/血浆鸭.md` },
  { id:  85, name: '西红柿土豆炖牛肉', emoji: '🥩', price: 0, desc: '西红柿土豆炖牛肉（腩）的特点就是还挺好吃，牛肉是优质蛋白，换成牛腩更好吃。', category: '肉菜', image: `${IMG.meat_dish}/西红柿土豆炖牛肉/abaaba_1.png`, tutorialUrl: `${R}/meat_dish/西红柿土豆炖牛肉/西红柿土豆炖牛肉.md` },
  { id:  86, name: '豆豉鲮鱼油麦菜', emoji: '🐟', price: 0, desc: '豆豉鲮鱼油麦菜是一到十分常见的菜，材料简单，操作方便，鲮鱼咸香，非常下饭。', category: '肉菜', image: `${IMG.meat_dish}/豆豉鲮鱼油麦菜/豆豉鲮鱼油麦菜成品.jpg`, tutorialUrl: `${R}/meat_dish/豆豉鲮鱼油麦菜/豆豉鲮鱼油麦菜.md` },
  { id:  87, name: '豉汁排骨', emoji: '🍖', price: 0, desc: '豉汁排骨是粤式茶楼经典蒸点，豉香浓郁，排骨滑嫩多汁，超下饭！', category: '肉菜', image: `${IMG.meat_dish}/豉汁排骨/豉汁排骨.jpg`, tutorialUrl: `${R}/meat_dish/豉汁排骨/豉汁排骨.md` },
  { id:  88, name: '豉汁蒸白鱔', emoji: '🍖', price: 0, desc: '- 白鱔（白鳝）', category: '肉菜', image: `${IMG.meat_dish}/豉汁蒸白鱔/豉汁蒸白鱔.jpeg`, tutorialUrl: `${R}/meat_dish/豉汁蒸白鱔/豉汁蒸白鱔.md` },
  { id:  89, name: '贵州辣子鸡', emoji: '🍗', price: 0, desc: '贵州人对吃鸡的执恋', category: '肉菜', image: `${IMG.meat_dish}/贵州辣子鸡/贵州辣子鸡.jpg`, tutorialUrl: `${R}/meat_dish/贵州辣子鸡/贵州辣子鸡.md` },
  { id:  90, name: '酱排骨', emoji: '🍖', price: 0, desc: '酱排骨其色泽酱红，肉质酥烂，骨香浓郁，汁浓味鲜，咸中带甜。', category: '肉菜', image: `${IMG.meat_dish}/酱排骨/1.jpeg`, tutorialUrl: `${R}/meat_dish/酱排骨/酱排骨.md` },
  { id:  91, name: '酱牛肉', emoji: '🥩', price: 0, desc: '家常酱牛肉营养丰富，味道香，不论是当作主食还是佐餐都很棒。一般初学者只需要 10 小时即可完成。', category: '肉菜', image: `${IMG.meat_dish}/酱牛肉/酱牛肉.jpg`, tutorialUrl: `${R}/meat_dish/酱牛肉/酱牛肉.md` },
  { id:  92, name: '醉排骨', emoji: '🍖', price: 0, desc: '醉排骨是福建省福州市特色传统名菜', category: '肉菜', image: `${IMG.meat_dish}/醉排骨/1.jpeg`, tutorialUrl: `${R}/meat_dish/醉排骨/醉排骨.md` },
  { id:  93, name: '青椒土豆炒肉', emoji: '🥘', price: 0, desc: '青椒土豆炒肉是一道荤素搭配的简单炒菜。一般初学者只需要 1 小时即可完成。贼下饭~', category: '肉菜', image: `${IMG.meat_dish}/青椒土豆炒肉/青椒土豆炒肉.jpg`, tutorialUrl: `${R}/meat_dish/青椒土豆炒肉/青椒土豆炒肉.md` },
  { id:  94, name: '香干肉丝', emoji: '🥘', price: 0, desc: '* 猪里脊（可以买超市切好且称重好的肉丝）', category: '肉菜', image: `${IMG.meat_dish}/香干肉丝/香干肉丝.jpg`, tutorialUrl: `${R}/meat_dish/香干肉丝/香干肉丝.md` },
  { id:  95, name: '香干芹菜炒肉', emoji: '🥘', price: 0, desc: '香干芹菜炒肉是一道非常简单的家常菜小炒，据说多吃芹菜对于高血压有很好的缓解作用，加上香干和猪肉一起翻炒，还是很美味的。一', category: '肉菜', image: `${IMG.meat_dish}/香干芹菜炒肉/香干芹菜炒肉.jpg`, tutorialUrl: `${R}/meat_dish/香干芹菜炒肉/香干芹菜炒肉.md` },
  { id:  96, name: '香煎五花肉', emoji: '🥘', price: 0, desc: '香煎五花肉一道简单易上手的菜。五花肉肥而不腻，生菜叶脆爽健康。稍微有下厨经验的人半小时便可制作完毕。', category: '肉菜', image: `${IMG.meat_dish}/香煎五花肉/香煎五花肉.jpg`, tutorialUrl: `${R}/meat_dish/香煎五花肉/香煎五花肉.md` },
  { id:  97, name: '香辣鸡爪煲', emoji: '🍗', price: 0, desc: '香辣鸡爪煲口感 Q 弹，香辣浓郁，回味无穷。', category: '肉菜', image: `${IMG.meat_dish}/香辣鸡爪煲/result1.jpg`, tutorialUrl: `${R}/meat_dish/香辣鸡爪煲/香辣鸡爪煲.md` },
  { id:  98, name: '鱼香茄子', emoji: '🐟', price: 0, desc: '这个菜真的超级下饭，当个干饭王吧。', category: '肉菜', image: `${IMG.meat_dish}/鱼香茄子/yxqz1.jpg`, tutorialUrl: `${R}/meat_dish/鱼香茄子/鱼香茄子.md` },
  { id:  99, name: '麻辣香锅', emoji: '🍖', price: 0, desc: '- 青菜（油菜、油麦菜、菠菜）', category: '肉菜', image: `${IMG.meat_dish}/麻辣香锅/麻辣香锅.jpg`, tutorialUrl: `${R}/meat_dish/麻辣香锅/麻辣香锅.md` },
  { id: 100, name: '黄油鸡', emoji: '🍗', price: 0, desc: '> Butter Chicken / Murgh Makhani(मुर्ग़ मखनी)— 印度黄油鸡咖喱', category: '肉菜', image: `${IMG.meat_dish}/黄油鸡/黄油鸡.jpg`, tutorialUrl: `${R}/meat_dish/黄油鸡/黄油鸡.md` },
  { id: 101, name: '黄瓜炒肉', emoji: '🥘', price: 0, desc: '每次制作前需要确定计划做几份。一份正好够 1 个人食用', category: '肉菜', image: `${IMG.meat_dish}/黄瓜炒肉/黄瓜炒肉.jpg`, tutorialUrl: `${R}/meat_dish/黄瓜炒肉/黄瓜炒肉.md` },
  { id: 102, name: '黔式腊肠娃娃菜', emoji: '🍖', price: 0, desc: '黔式腊肠娃娃菜不需要掌握火候，也无需调料，非常适合懒癌的菜。制作时间 15 分钟，口味近似于川菜、湘菜，却是西南菜系中鲜', category: '肉菜', image: `${IMG.meat_dish}/黔式腊肠娃娃菜/黔式腊肠娃娃菜.jpg`, tutorialUrl: `${R}/meat_dish/黔式腊肠娃娃菜/黔式腊肠娃娃菜.md` },
  { id:  30, name: '蛋炒饭', emoji: '🍳', price: 0, desc: '粒粒分明，蛋香浓郁，简单美味的经典炒饭', category: '主食', image: `${R}/staple/微波炉腊肠煲仔饭/微波炉腊肠煲仔饭.png`, tutorialUrl: `${R}/staple/蛋炒饭/蛋炒饭.md` },
  { id:  31, name: '手工水饺', emoji: '🥟', price: 0, desc: '非常好吃的主食，饱肚且易于消化', category: '主食', image: `${R}/staple/意式肉酱面/final.jpg`, tutorialUrl: `${R}/staple/手工水饺/手工水饺.md` },
  { id:  32, name: '炸酱面', emoji: '🍜', price: 0, desc: '经典北京家常面，酱香浓郁，劲道爽口', category: '主食', image: `${R}/staple/老友猪肉粉/老友猪肉粉.jpg`, tutorialUrl: `${R}/staple/炸酱面/炸酱面.md` },
  { id:  33, name: '扬州炒饭', emoji: '🍚', price: 0, desc: '蛋炒饭的升级版，配料丰富，色泽金黄', category: '主食', image: `${IMG.staple}/扬州炒饭/veg.png`, tutorialUrl: `${R}/staple/扬州炒饭/扬州炒饭.md` },
  { id:  34, name: '葱油拌面', emoji: '🍜', price: 0, desc: '经典上海家常面，葱香浓郁，简单美味', category: '主食', image: `${R}/staple/意式肉酱面/spaghetti.jpg`, tutorialUrl: `${R}/staple/葱油拌面/葱油拌面.md` },
  { id:  35, name: '照烧鸡腿饭', emoji: '🍱', price: 0, desc: '金黄诱人，甜咸交织，酱香浓郁下饭神器', category: '主食', image: `${R}/staple/空气炸锅照烧鸡饭/空气炸锅照烧鸡饭.jpg`, tutorialUrl: `${R}/staple/照烧鸡腿饭/照烧鸡腿饭.md` },
  { id:  36, name: '日式咖喱饭', emoji: '🍛', price: 0, desc: '香浓咖喱搭配米饭，口感丰富令人回味', category: '主食', image: `${IMG.staple}/日式咖喱饭/成品.jpg`, tutorialUrl: `${R}/staple/日式咖喱饭/日式咖喱饭.md` },
  { id:  37, name: '蛋包饭', emoji: '🍳', price: 0, desc: '日式经典家常菜，炒饭与嫩滑蛋皮完美结合', category: '主食', image: `${R}/staple/微波炉腊肠煲仔饭/微波炉腊肠煲仔饭.png`, tutorialUrl: `${R}/staple/蛋包饭/蛋包饭.md` },
  { id:  38, name: '韩式拌饭', emoji: '🍚', price: 0, desc: '色彩丰富，营养均衡，拌匀后香味四溢', category: '主食', image: `${IMG.staple}/韩式拌饭/韩式拌饭.png`, tutorialUrl: `${R}/staple/韩式拌饭/韩式拌饭.md` },
  { id:  39, name: '热干面', emoji: '🍜', price: 0, desc: '武汉经典早餐，芝麻酱香浓，劲道爽口', category: '主食', image: `${R}/staple/意式肉酱面/final.jpg`, tutorialUrl: `${R}/staple/热干面/热干面.md` },
  { id:  40, name: '螺蛳粉', emoji: '🍜', price: 0, desc: '正宗的螺蛳粉是不臭的，鲜辣爽滑', category: '主食', image: `${R}/staple/老友猪肉粉/老友猪肉粉.jpg`, tutorialUrl: `${R}/staple/螺蛳粉/螺蛳粉.md` },
  { id:  50, name: '紫菜蛋花汤', emoji: '🍲', price: 0, desc: '紫菜鲜香，蛋花飘逸，清淡暖胃', category: '汤类', image: `${R}/soup/玉米排骨汤/玉米排骨汤.jpeg`, tutorialUrl: `${R}/soup/紫菜蛋花汤/紫菜蛋花汤.md` },
  { id:  51, name: '西红柿鸡蛋汤', emoji: '🍅', price: 0, desc: '酸甜可口，营养丰富，家常快手暖汤', category: '汤类', image: `${R}/soup/菌菇炖乳鸽/菌菇炖乳鸽.jpg`, tutorialUrl: `${R}/soup/西红柿鸡蛋汤/西红柿鸡蛋汤.md` },
  { id:  52, name: '玉米排骨汤', emoji: '🌽', price: 0, desc: '清甜的玉米配上软烂排骨，营养丰富', category: '汤类', image: `${IMG.soup}/玉米排骨汤/玉米排骨汤.jpeg`, tutorialUrl: `${R}/soup/玉米排骨汤/玉米排骨汤.md` },
  { id:  53, name: '皮蛋瘦肉粥', emoji: '🍚', price: 0, desc: '粥底绵滑，皮蛋鲜香，瘦肉嫩滑', category: '汤类', image: `${R}/soup/银耳莲子粥/银耳莲子粥.png`, tutorialUrl: `${R}/soup/皮蛋瘦肉粥/皮蛋瘦肉粥.md` },
  { id:  54, name: '罗宋汤', emoji: '🥣', price: 0, desc: '源自俄罗斯的经典浓汤，酸甜开胃暖身', category: '汤类', image: `${R}/soup/菌菇炖乳鸽/菌菇炖乳鸽.jpg`, tutorialUrl: `${R}/soup/罗宋汤/罗宋汤.md` },
  { id:  55, name: '小米粥', emoji: '🌾', price: 0, desc: '富含多种维生素，养胃暖心的健康粥', category: '汤类', image: `${R}/soup/银耳莲子粥/银耳莲子粥.png`, tutorialUrl: `${R}/soup/小米粥/小米粥.md` },
  { id:  56, name: '银耳莲子粥', emoji: '🍚', price: 0, desc: '银耳软糯，莲子清甜，滋阴润燥', category: '汤类', image: `${IMG.soup}/银耳莲子粥/银耳莲子粥.png`, tutorialUrl: `${R}/soup/银耳莲子粥/银耳莲子粥.md` },
  { id:  57, name: '奶油蘑菇汤', emoji: '🍄', price: 0, desc: '浓郁奶香配鲜蘑菇，西式浓汤香醇顺滑', category: '汤类', image: `${R}/soup/菌菇炖乳鸽/菌菇炖乳鸽.jpg`, tutorialUrl: `${R}/soup/奶油蘑菇汤/奶油蘑菇汤.md` },
  { id:  60, name: '柠檬水', emoji: '🍋', price: 0, desc: '新鲜柠檬切片，酸甜清凉解渴', category: '饮品', image: `${IMG.drink}/柠檬水/柠檬水.jpg`, tutorialUrl: `${R}/drink/柠檬水/柠檬水.md` },
  { id:  61, name: '酸梅汤', emoji: '🫐', price: 0, desc: '古法熬制，酸甜爽口，消暑开胃', category: '饮品', image: `${R}/drink/百香果橙子特调/tea-version.jpg`, tutorialUrl: `${R}/drink/酸梅汤/酸梅汤.md` },
  { id:  62, name: '奶茶', emoji: '🧋', price: 0, desc: '简单易做的经典奶茶，香醇顺滑', category: '饮品', image: `${R}/drink/耙耙柑茶/citrus-tea.jpg`, tutorialUrl: `${R}/drink/奶茶/奶茶.md` },
  { id:  63, name: '杨枝甘露', emoji: '🥭', price: 0, desc: '芒果清香，椰奶丝滑，港式甜品饮料', category: '饮品', image: `${R}/drink/砂糖椰子冰沙/砂糖椰子冰沙-1.jpg`, tutorialUrl: `${R}/drink/杨枝甘露/杨枝甘露.md` },
  { id:  64, name: '冰粉', emoji: '🧊', price: 0, desc: '清凉透彻，Q弹爽口，夏日消暑圣品', category: '饮品', image: `${IMG.drink}/冰粉/石凉粉(冰粉)成品1.jpg`, tutorialUrl: `${R}/drink/冰粉/冰粉.md` },
  { id:  65, name: '印度奶茶', emoji: '☕', price: 0, desc: '香料奶茶，浓郁异域风情，香甜暖心', category: '饮品', image: `${R}/drink/耙耙柑茶/citrus-tea.jpg`, tutorialUrl: `${R}/drink/印度奶茶/印度奶茶.md` },
  { id:  66, name: '酒酿醪糟', emoji: '🍶', price: 0, desc: '甜糯香醇，自制发酵米酒，暖胃养身', category: '饮品', image: `${IMG.drink}/酒酿醪糟/酒酿米糕.jpeg`, tutorialUrl: `${R}/drink/酒酿醪糟/酒酿醪糟.md` },

  // ======= 饮品（续）=======
  { id:  67, name: 'B52轰炸机', emoji: '🧨', price: 0, desc: '经典鸡尾酒，三层酒液分明，喝法独特需要短吸管', category: '饮品', image: `${IMG.drink}/柠檬水/柠檬水.jpg`, tutorialUrl: `${R}/drink/B52轰炸机.md` },
  { id:  68, name: 'Mojito莫吉托', emoji: '🍃', price: 0, desc: '传统古巴高球鸡尾酒，清爽薄荷香，酸甜怡人', category: '饮品', image: `${IMG.drink}/柠檬水/柠檬水.jpg`, tutorialUrl: `${R}/drink/Mojito莫吉托.md` },
  { id:  69, name: '冬瓜茶', emoji: '🥒', price: 0, desc: '清爽解渴的传统饮料，冬瓜甘甜消暑', category: '饮品', image: `${IMG.drink}/柠檬水/柠檬水.jpg`, tutorialUrl: `${R}/drink/冬瓜茶.md` },
  { id:  70, name: '可乐桶', emoji: '🪣', price: 0, desc: '派对聚会必备混合饮料，酸甜多味', category: '饮品', image: `${IMG.drink}/柠檬水/柠檬水.jpg`, tutorialUrl: `${R}/drink/可乐桶.md` },
  { id:  71, name: '奇异果菠菜特调', emoji: '🥝', price: 0, desc: '新鲜奇异果与菠菜的健康特调，营养丰富', category: '饮品', image: `${IMG.drink}/奇异果菠菜特调/kiwi-example.jpg`, tutorialUrl: `${R}/drink/奇异果菠菜特调/奇异果菠菜特调.md` },
  { id:  72, name: '泰国手标红茶', emoji: '🧡', price: 0, desc: '原产泰国的红茶，浓郁醇厚，奶茶绝佳底料', category: '饮品', image: `${IMG.drink}/泰国手标红茶/泰国手标红茶.jpg`, tutorialUrl: `${R}/drink/泰国手标红茶/泰国手标红茶.md` },
  { id:  73, name: '海边落日', emoji: '🌅', price: 0, desc: '调酒师经典作品，色泽如夕阳，酸甜适口', category: '饮品', image: `${IMG.drink}/海边落日/海边落日.jpg`, tutorialUrl: `${R}/drink/海边落日/海边落日.md` },
  { id:  74, name: '牛油果拉西', emoji: '🥑', price: 0, desc: '绵密牛油果与酸奶完美融合，顺滑清甜健康饮品', category: '饮品', image: `${IMG.drink}/耙耙柑茶/citrus-tea.jpg`, tutorialUrl: `${R}/drink/牛油果拉西.md` },
  { id:  75, name: '百香果橙子特调', emoji: '🧡', price: 0, desc: '百香果与橙子的完美搭配，酸甜清爽多味', category: '饮品', image: `${IMG.drink}/百香果橙子特调/tea-version.jpg`, tutorialUrl: `${R}/drink/百香果橙子特调/百香果橙子特调.md` },
  { id:  76, name: '砂糖椰子冰沙', emoji: '🥥', price: 0, desc: '制作极其快速的冰沙，椰香浓郁口感丰富', category: '饮品', image: `${IMG.drink}/砂糖椰子冰沙/砂糖椰子冰沙-1.jpg`, tutorialUrl: `${R}/drink/砂糖椰子冰沙/砂糖椰子冰沙.md` },
  { id:  77, name: '耙耙柑茶', emoji: '🍊', price: 0, desc: '新鲜柑橘茶饮，香气清雅，清甜适口', category: '饮品', image: `${IMG.drink}/耙耙柑茶/citrus-tea.jpg`, tutorialUrl: `${R}/drink/耙耙柑茶/耙耙柑茶.md` },
  { id:  78, name: '菠萝咖啡特调', emoji: '☕', price: 0, desc: '酸甜可口的创意饮料，菠萝与咖啡的灵动碰撞', category: '饮品', image: `${IMG.drink}/菠萝咖啡特调/菠萝咖啡特调.png`, tutorialUrl: `${R}/drink/菠萝咖啡特调/菠萝咖啡特调.md` },
  { id:  79, name: '金汤力', emoji: '🥃', price: 0, desc: '经典鸡尾酒，金酒搭配奎宁水，清爽怡人', category: '饮品', image: `${IMG.drink}/金汤力/gin-tonic.jpg`, tutorialUrl: `${R}/drink/金汤力/金汤力.md` },
  { id:  80, name: '金菲士', emoji: '✨', price: 0, desc: '经典鸡尾酒，金酒搭配汽水柠檬，爽口清新', category: '饮品', image: `${IMG.drink}/金菲士/gin-fizz.jpg`, tutorialUrl: `${R}/drink/金菲士/金菲士.md` },
  { id:  81, name: '长岛冰茶', emoji: '🍹', price: 0, desc: '烈酒集合体，多种酒类混调，后劲十足', category: '饮品', image: `${IMG.drink}/柠檬水/柠檬水.jpg`, tutorialUrl: `${R}/drink/长岛冰茶.md` },

  // ======= 水产 =======
  { id:  82, name: '蒜蓉虾', emoji: '🦐', price: 0, desc: '蒜香诱人，虾肉鲜美，简单易做的经典快手菜', category: '水产', image: `${IMG.aquatic}/蒜蓉虾/1.jpeg`, tutorialUrl: `${R}/aquatic/蒜蓉虾/蒜蓉虾.md` },
  { id:  83, name: '蒜香黄油虾', emoji: '🦐', price: 0, desc: '黄油香浓，蒜香四溢，高档又简单的虾菜', category: '水产', image: `${IMG.aquatic}/蒜香黄油虾/1.jpeg`, tutorialUrl: `${R}/aquatic/蒜香黄油虾/蒜香黄油虾.md` },
  { id:  84, name: '蛏抱蛋', emoji: '🥚', price: 0, desc: '贝类与鸡蛋的完美结合，鲜香软滑', category: '水产', image: `${IMG.aquatic}/蛏抱蛋/1.jpeg`, tutorialUrl: `${R}/aquatic/蛏抱蛋/蛏抱蛋.md` },
  { id:  85, name: '香煎翘嘴鱼', emoji: '🐟', price: 0, desc: '外酥里嫩，香味浓郁，烹鱼的经典做法', category: '水产', image: `${IMG.aquatic}/香煎翘嘴鱼/1.jpeg`, tutorialUrl: `${R}/aquatic/香煎翘嘴鱼/香煎翘嘴鱼.md` },
  { id:  86, name: '鲤鱼炖白菜', emoji: '🍲', price: 0, desc: '清汤鲜美，白菜吸汁，营养丰富的家常炖菜', category: '水产', image: `${IMG.aquatic}/鲤鱼炖白菜/1.jpeg`, tutorialUrl: `${R}/aquatic/鲤鱼炖白菜/鲤鱼炖白菜.md` },
  { id:  87, name: '鳊鱼炖豆腐', emoji: '🍲', price: 0, desc: '鱼肉细嫩，豆腐吸汤，滋补暖心的炖汤', category: '水产', image: `${IMG.aquatic}/鳊鱼炖豆腐/1.jpeg`, tutorialUrl: `${R}/aquatic/鳊鱼炖豆腐/鳊鱼炖豆腐.md` },
  { id:  88, name: '黄油煎虾', emoji: '🦐', price: 0, desc: '黄油香浓，虾肉鲜嫩，简单又高级', category: '水产', image: `${IMG.aquatic}/黄油煎虾/1.jpeg`, tutorialUrl: `${R}/aquatic/黄油煎虾/黄油煎虾.md` },
  { id:  89, name: '咖喱炒蟹', emoji: '🦀', price: 0, desc: '咖喱香浓，蟹肉鲜美，印式风味海鲜菜', category: '水产', image: `${IMG.aquatic}/咖喱炒蟹/1.jpeg`, tutorialUrl: `${R}/aquatic/咖喱炒蟹.md` },
  { id:  90, name: '响油鳝丝', emoji: '🐍', price: 0, desc: '油香诱人，鳝鱼鲜嫩，川菜经典风味', category: '水产', image: `${IMG.aquatic}/响油鳝丝/1.jpeg`, tutorialUrl: `${R}/aquatic/响油鳝丝.md` },
  { id:  91, name: '微波葱姜黑鳕鱼', emoji: '🐟', price: 0, desc: '简便快手，葱姜香浓，微波炉就能做的鱼菜', category: '水产', image: `${IMG.aquatic}/微波葱姜黑鳕鱼/1.jpeg`, tutorialUrl: `${R}/aquatic/微波葱姜黑鳕鱼.md` },
  { id:  92, name: '水煮鱼', emoji: '🌶️', price: 0, desc: '麻辣汤汁，鱼肉鲜嫩，川味下饭经典菜', category: '水产', image: `${IMG.aquatic}/水煮鱼/1.jpeg`, tutorialUrl: `${R}/aquatic/水煮鱼.md` },
  { id:  93, name: '清蒸生蚝', emoji: '🦪', price: 0, desc: '鲜甜多汁，蒸出原汁原味，简单营养', category: '水产', image: `${IMG.aquatic}/清蒸生蚝/1.jpeg`, tutorialUrl: `${R}/aquatic/清蒸生蚝.md` },
  { id:  94, name: '红烧鱼', emoji: '🐟', price: 0, desc: '色泽红亮，鱼肉软烂，下饭绝佳的经典菜', category: '水产', image: `${IMG.aquatic}/红烧鱼/1.jpeg`, tutorialUrl: `${R}/aquatic/红烧鱼.md` },
  { id:  95, name: '红烧鱼头', emoji: '🐟', price: 0, desc: '鱼脑鲜香，胶质丰富，营养价值高', category: '水产', image: `${IMG.aquatic}/红烧鱼头/1.jpeg`, tutorialUrl: `${R}/aquatic/红烧鱼头.md` },
  { id:  96, name: '红烧鲤鱼', emoji: '🐟', price: 0, desc: '鲤鱼肉质细嫩，红烧后入味，家常必备菜', category: '水产', image: `${IMG.aquatic}/红烧鲤鱼/1.jpeg`, tutorialUrl: `${R}/aquatic/红烧鲤鱼.md` },
  { id:  97, name: '肉蟹煲', emoji: '🦀', price: 0, desc: '蟹肉饱满，汤汁鲜美，高档餐桌必备', category: '水产', image: `${IMG.aquatic}/肉蟹煲/1.jpeg`, tutorialUrl: `${R}/aquatic/肉蟹煲.md` },
  { id:  98, name: '酱炖蟹', emoji: '🦀', price: 0, desc: '豉香浓郁，蟹肉鲜甜，家常简单做法', category: '水产', image: `${IMG.aquatic}/酱炖蟹/1.jpeg`, tutorialUrl: `${R}/aquatic/酱炖蟹.md` },
  { id:  99, name: '小龙虾', emoji: '🦞', price: 0, desc: '肉质细嫩鲜嫩多汁，干净卫生，虾类料理的经典', category: '水产', image: `${IMG.aquatic}/小龙虾/成品.jpg`, tutorialUrl: `${R}/aquatic/小龙虾/小龙虾.md` },
  { id: 100, name: '干煎阿根廷红虾', emoji: '🦐', price: 0, desc: '天生红透，肉质白如凝脂，细腻腴滑鲜嫩', category: '水产', image: `${IMG.aquatic}/干煎阿根廷红虾/干煎阿根廷红虾.jpg`, tutorialUrl: `${R}/aquatic/干煎阿根廷红虾/干煎阿根廷红虾.md` },
  { id: 101, name: '油焖大虾', emoji: '🦐', price: 0, desc: '虾肉饱满鲜美，油香四溢，快手海鲜佳肴', category: '水产', image: `${IMG.aquatic}/油焖大虾/油焖大虾.jpg`, tutorialUrl: `${R}/aquatic/油焖大虾/油焖大虾.md` },
  { id: 102, name: '混合烤鱼', emoji: '🐟', price: 0, desc: '外香里嫩，火候掌握恰到好处，烤鱼经典做法', category: '水产', image: `${IMG.aquatic}/混合烤鱼/烤鱼.jpg`, tutorialUrl: `${R}/aquatic/混合烤鱼/烤鱼.md` },
  { id: 103, name: '清蒸鲈鱼', emoji: '🐟', price: 0, desc: '鱼肉鲜嫩，清蒸保留原汁原味，清淡健康', category: '水产', image: `${IMG.aquatic}/清蒸鲈鱼/摆盘.jpg`, tutorialUrl: `${R}/aquatic/清蒸鲈鱼/清蒸鲈鱼.md` },
  { id: 104, name: '白灼虾', emoji: '🦐', price: 0, desc: '简单容错低失败率，营养丰富有满足感', category: '水产', image: `${IMG.aquatic}/白灼虾/白灼虾.webp`, tutorialUrl: `${R}/aquatic/白灼虾/白灼虾.md` },
  { id: 105, name: '糖醋鲤鱼', emoji: '🐟', price: 0, desc: '甜酸适口，鱼肉饱满，酸酸甜甜下饭菜', category: '水产', image: `${IMG.aquatic}/糖醋鲤鱼/成品.jpg`, tutorialUrl: `${R}/aquatic/糖醋鲤鱼/糖醋鲤鱼.md` },
  { id: 106, name: '芥末黄油罗氏虾', emoji: '🦐', price: 0, desc: '做法简单味道美味，具有新意的海鲜创意菜', category: '水产', image: `${IMG.aquatic}/芥末黄油罗氏虾/芥末黄油罗氏虾.jpg`, tutorialUrl: `${R}/aquatic/芥末黄油罗氏虾/芥末黄油罗氏虾.md` },
  { id: 107, name: '葱油桂鱼', emoji: '🐟', price: 0, desc: '葱香浓郁，鱼肉细嫩，江浙菜系经典佳肴', category: '水产', image: `${IMG.aquatic}/葱油桂鱼/10.jpg`, tutorialUrl: `${R}/aquatic/葱油桂鱼/葱油桂鱼.md` },
  { id: 108, name: '葱烧海参', emoji: '🌰', price: 0, desc: '海参泡发营养丰富，葱香四溢的滋补菜', category: '水产', image: `${IMG.aquatic}/葱烧海参/海参.jpeg`, tutorialUrl: `${R}/aquatic/葱烧海参/葱烧海参.md` },

  // ======= 调味料 =======
  { id: 126, name: '油泼辣子', emoji: '🌶️', price: 0, desc: '热油泼出香气，辣椒香浓郁，家常必备调味料', category: '调味料', image: `${IMG.condiment}/油泼辣子/油泼辣子.jpg`, tutorialUrl: `${R}/condiment/油泼辣子/油泼辣子.md` },
  { id: 127, name: '油酥', emoji: '🥣', price: 0, desc: '面粉与热油混合，使饼子层层分明外酥里软', category: '调味料', image: `${IMG.condiment}/油泼辣子/油泼辣子.jpg`, tutorialUrl: `${R}/condiment/油酥.md` },
  { id: 128, name: '炸串酱料', emoji: '🍶', price: 0, desc: '炸串的标配酱料，增添特殊香味和口感', category: '调味料', image: `${IMG.condiment}/油泼辣子/油泼辣子.jpg`, tutorialUrl: `${R}/condiment/炸串酱料.md` },
  { id: 129, name: '简易版炒糖色', emoji: '🍯', price: 0, desc: '简便易学的糖色做法，为菜肴增添色泽', category: '调味料', image: `${IMG.condiment}/油泼辣子/油泼辣子.jpg`, tutorialUrl: `${R}/condiment/简易版炒糖色.md` },
  { id: 130, name: '糖醋汁', emoji: '🍯', price: 0, desc: '由清水白糖白醋制成，用于糖醋菜肴的制作', category: '调味料', image: `${IMG.condiment}/油泼辣子/油泼辣子.jpg`, tutorialUrl: `${R}/condiment/糖醋汁.md` },
  { id: 131, name: '草莓酱', emoji: '🍓', price: 0, desc: '鲜甜草莓熬制而成，抹在面包上非常好吃', category: '调味料', image: `${IMG.condiment}/草莓酱/做好的草莓酱.png`, tutorialUrl: `${R}/condiment/草莓酱/草莓酱.md` },
  { id: 132, name: '葱油', emoji: '🧄', price: 0, desc: '热油萃取香葱等香辛料，用于调馅或出锅明油', category: '调味料', image: `${IMG.condiment}/油泼辣子/油泼辣子.jpg`, tutorialUrl: `${R}/condiment/葱油.md` },
  { id: 133, name: '蒜香酱油', emoji: '🧄', price: 0, desc: '蒜香与酱油的完美结合，提升菜肴风味', category: '调味料', image: `${IMG.condiment}/油泼辣子/油泼辣子.jpg`, tutorialUrl: `${R}/condiment/蒜香酱油.md` },
  { id: 134, name: '蔗糖糖浆', emoji: '🥤', price: 0, desc: '蔗糖溶解制成，用于冷饮增甜的糖浆', category: '调味料', image: `${IMG.condiment}/蔗糖糖浆/bottle.jpg`, tutorialUrl: `${R}/condiment/蔗糖糖浆/蔗糖糖浆.md` },

  // ======= 甜点 =======
  { id: 135, name: '反沙芋头', emoji: '🍠', price: 0, desc: '芋头外层裹着糖衣，松软香甜的经典甜点', category: '甜点', image: `${IMG.dessert}/反沙芋头/反沙芋头成品.jpg`, tutorialUrl: `${R}/dessert/反沙芋头/反沙芋头.md` },
  { id: 136, name: '咖啡椰奶冻', emoji: '☕', price: 0, desc: '咖啡香与椰奶的完美结合，冰爽甜蜜', category: '甜点', image: `${IMG.dessert}/咖啡椰奶冻/咖啡椰奶冻.png`, tutorialUrl: `${R}/dessert/咖啡椰奶冻/咖啡椰奶冻.md` },
  { id: 137, name: '奥利奥冰淇淋', emoji: '🍦', price: 0, desc: '纯动物奶油不腻口，简单但好吃的手工冰淇淋', category: '甜点', image: `${IMG.dessert}/咖啡椰奶冻/咖啡椰奶冻.png`, tutorialUrl: `${R}/dessert/奥利奥冰淇淋/奥利奥冰淇淋.md` },
  { id: 138, name: '戚风蛋糕', emoji: '🎂', price: 0, desc: '烘焙入门菜品，口感细腻绵软，令人回味', category: '甜点', image: `${IMG.dessert}/戚风蛋糕/DSC08716.jpg`, tutorialUrl: `${R}/dessert/戚风蛋糕/戚风蛋糕.md` },
  { id: 139, name: '提拉米苏', emoji: '🍰', price: 0, desc: '意大利经典甜点，浓郁的咖啡香，入口即化', category: '甜点', image: `${IMG.dessert}/提拉米苏/提拉米苏成品.jpg`, tutorialUrl: `${R}/dessert/提拉米苏/提拉米苏.md` },
  { id: 140, name: '无厨师机蜂蜜面包', emoji: '🍞', price: 0, desc: '手工揉面，蜂蜜香甜，松软可口的面包', category: '甜点', image: `${IMG.dessert}/无厨师机蜂蜜面包/无厨师机蜂蜜面包.jpg`, tutorialUrl: `${R}/dessert/无厨师机蜂蜜面包/无厨师机蜂蜜面包.md` },
  { id: 141, name: '炸鲜奶', emoji: '🧈', price: 0, desc: '外脆里嫩，香甜软滑的港式经典小食', category: '甜点', image: `${IMG.dessert}/炸鲜奶/炸鲜奶.jpg`, tutorialUrl: `${R}/dessert/炸鲜奶/炸鲜奶.md` },
  { id: 142, name: '烤箱版巴斯克芝士蛋糕', emoji: '🍰', price: 0, desc: '金黄的焦香外皮，奶油软糯内心，浓郁芝士风味', category: '甜点', image: `${IMG.dessert}/烤箱版巴斯克芝士蛋糕/烤箱版巴斯克芝士蛋糕.jpg`, tutorialUrl: `${R}/dessert/烤箱版巴斯克芝士蛋糕/烤箱版巴斯克芝士蛋糕.md` },
  { id: 143, name: '烤蛋挞', emoji: '🥧', price: 0, desc: '脆皮酥香，馅料幼滑，葡式经典蛋挞', category: '甜点', image: `${IMG.dessert}/烤蛋挞/烤蛋挞.png`, tutorialUrl: `${R}/dessert/烤蛋挞/烤蛋挞.md` },
  { id: 144, name: '玛格丽特饼干', emoji: '🍪', price: 0, desc: '黄油香浓，入口即化，简单易做的法式饼干', category: '甜点', image: `${IMG.dessert}/玛格丽特饼干/玛格丽特饼干.jpg`, tutorialUrl: `${R}/dessert/玛格丽特饼干/玛格丽特饼干.md` },
  { id: 145, name: '红柚蛋糕', emoji: '🍰', price: 0, desc: '空气炸锅烘焙，红柚清香，适合单人食用', category: '甜点', image: `${IMG.dessert}/红柚蛋糕/咖啡椰奶冻.png`, tutorialUrl: `${R}/dessert/红柚蛋糕/红柚蛋糕.md` },
  { id: 146, name: '芋泥雪媚娘', emoji: '🍡', price: 0, desc: '软糯的糯米皮，香滑的芋泥馅，创意甜点', category: '甜点', image: `${IMG.dessert}/芋泥雪媚娘/芋泥雪媚娘成品.jpg`, tutorialUrl: `${R}/dessert/芋泥雪媚娘/芋泥雪媚娘.md` },
  { id: 147, name: '英式司康', emoji: '🥐', price: 0, desc: '英式传统下午茶点心，酥松爽脆，配果酱食用', category: '甜点', image: `${IMG.dessert}/英式司康/英式司康.png`, tutorialUrl: `${R}/dessert/英式司康/英式司康.md` },
  { id: 148, name: '草莓冰淇淋', emoji: '🍓', price: 0, desc: '新鲜草莓风味，冰爽甜蜜的手工冰淇淋', category: '甜点', image: `${IMG.dessert}/咖啡椰奶冻/咖啡椰奶冻.png`, tutorialUrl: `${R}/dessert/草莓冰淇淋/草莓冰淇淋.md` },
  { id: 149, name: '酸奶意式奶冻', emoji: '🍨', price: 0, desc: '酸奶清爽，意式奶冻顺滑，双重口感享受', category: '甜点', image: `${IMG.dessert}/酸奶意式奶冻/酸奶意式奶冻.png`, tutorialUrl: `${R}/dessert/酸奶意式奶冻/酸奶意式奶冻.md` },
  { id: 150, name: '雪花酥', emoji: '❄️', price: 0, desc: '酥脆可口，蔓越莓与坚果的甜蜜结合', category: '甜点', image: `${IMG.dessert}/雪花酥/雪花酥成品.jpg`, tutorialUrl: `${R}/dessert/雪花酥/雪花酥.md` },
  { id: 151, name: '龟苓膏', emoji: '🍲', price: 0, desc: '中医保健甜品，苦中带甜，清热祛湿', category: '甜点', image: `${IMG.dessert}/龟苓膏/龟苓膏成品.jpg`, tutorialUrl: `${R}/dessert/龟苓膏/龟苓膏.md` },
  
  // ======= 半成品 =======
  { id: 152, name: '凉皮', emoji: '🍜', price: 0, desc: '* 凉皮、面筋', category: '半成品', image: `${IMG.semi_finished}/凉皮/凉皮.jpg`, tutorialUrl: `${R}/semi-finished/凉皮/凉皮.md` },
  { id: 153, name: '半成品意面', emoji: '🍝', price: 0, desc: '意大利面🍝和中国面条口感上的区别主要是因为它是由小麦品种中最硬质的杜兰(durum)磨粉制成的。', category: '半成品', image: `${IMG.semi_finished}/半成品意面/半成品意面.jpg`, tutorialUrl: `${R}/semi-finished/半成品意面/半成品意面.md` },
  { id: 154, name: '懒人蛋挞', emoji: '🥧', price: 0, desc: '蛋挞是一道常见的可口甜品，通常而言制作蛋挞是需要调和蛋挞液和制作蛋挞皮的，这个过程比较复杂和耗时，但是网购半成品恰恰解决', category: '半成品', image: `${IMG.semi_finished}/懒人蛋挞/懒人蛋挞.png`, tutorialUrl: `${R}/semi-finished/懒人蛋挞/懒人蛋挞.md` },
  { id: 155, name: '炸薯条', emoji: '🍟', price: 0, desc: '薯条🍟是一种土豆🥔\马铃薯🥔\洋芋🥔切成条状之后再油炸而成的快餐食物（在有的国家可能不算快餐），非常适合。相较于油炸，空', category: '半成品', image: `${IMG.semi_finished}/炸薯条/炸薯条.jpg`, tutorialUrl: `${R}/semi-finished/炸薯条/炸薯条.md` },
  { id: 156, name: '牛油火锅底料', emoji: '🍲', price: 0, desc: '重庆火锅又称毛肚火锅或麻辣火锅，是中国传统饮食方式之一。', category: '半成品', image: `${IMG.semi_finished}/牛油火锅底料/牛油火锅底料.jpg`, tutorialUrl: `${R}/semi-finished/牛油火锅底料/牛油火锅底料.md` },
  { id: 157, name: '空气炸锅羊排', emoji: '🐑', price: 0, desc: '空气炸锅羊排超级懒人版，味道尚可，主要看羊排的品质。', category: '半成品', image: `${IMG.semi_finished}/空气炸锅羊排/羊排.jpg`, tutorialUrl: `${R}/semi-finished/空气炸锅羊排/空气炸锅羊排.md` },
  { id: 158, name: '空气炸锅鸡翅中', emoji: '🍗', price: 0, desc: '空气炸锅做鸡翅中方便，这样自带油脂的食物味道很好，比 KFC 的好吃，吃完不**用洗碗洗锅**。', category: '半成品', image: `${IMG.semi_finished}/空气炸锅鸡翅中/鸡翅中_1.jpg`, tutorialUrl: `${R}/semi-finished/空气炸锅鸡翅中/空气炸锅鸡翅中.md` },
  { id: 159, name: '速冻水饺', emoji: '🥟', price: 0, desc: '饺子是一种源自中国的一种以面皮包馅、形如半月或元宝形的食物。饺子是在农历新年和冬至等节日的重要食品。通常由碎肉和蔬菜馅料', category: '半成品', image: `${IMG.semi_finished}/速冻水饺/速冻水饺.jpg`, tutorialUrl: `${R}/semi-finished/速冻水饺/速冻水饺.md` },
  { id: 160, name: '速冻汤圆', emoji: '🍡', price: 0, desc: '速冻汤圆是一道简单易做的菜。一般初学者只需要 6 分钟即可完成。', category: '半成品', image: `${IMG.semi_finished}/速冻汤圆/速冻汤圆.jpg`, tutorialUrl: `${R}/semi-finished/速冻汤圆/速冻汤圆.md` },
  { id: 161, name: '速冻馄饨', emoji: '🥟', price: 0, desc: '馄饨是一种起源于中国的一种民间传统面食，[饺子](./速冻水饺.md)由其分化而出，有皮薄馅嫩、汤清味鲜的特点。', category: '半成品', image: `${IMG.semi_finished}/速冻馄饨/速冻馄饨.jpg`, tutorialUrl: `${R}/semi-finished/速冻馄饨/速冻馄饨.md` }
,  
  // ======= 汤类（续）=======
  { id: 162, name: '勾芡香菇汤', emoji: '🍲', price: 0, desc: '鲜香菇除了拿来和肉炒外，其实拿来做浓浓的勾芡汤也是非常可口的。', category: '汤类', image: `${IMG.soup}/勾芡香菇汤/1.jpeg`, tutorialUrl: `${R}/soup/勾芡香菇汤/勾芡香菇汤.md` },
  { id: 163, name: '排骨苦瓜汤', emoji: '🍲', price: 0, desc: '排骨苦瓜汤是一道味道鲜美且容易烹饪的汤。不过汤的烹饪时间都较长，一般来说最好提前 4 个小时开始进行准备。', category: '汤类', image: `${IMG.soup}/排骨苦瓜汤/排骨苦瓜汤.md`, tutorialUrl: `${R}/soup/排骨苦瓜汤/排骨苦瓜汤.md` },
  { id: 164, name: '昂刺鱼豆腐汤', emoji: '🍲', price: 0, desc: '- 昂刺鱼/沙光鱼 豆腐汤 刺少 肉嫩 营养丰盛、适合任何年龄的小伙伴', category: '汤类', image: `${IMG.soup}/昂刺鱼豆腐汤/昂刺鱼豆腐汤02.jpg`, tutorialUrl: `${R}/soup/昂刺鱼豆腐汤/昂刺鱼豆腐汤.md` },
  { id: 165, name: '朱雀汤', emoji: '🍲', price: 0, desc: '预估烹饪难度：★', category: '汤类', image: `${IMG.soup}/朱雀汤/朱雀汤.jpg`, tutorialUrl: `${R}/soup/朱雀汤/朱雀汤.md` },
  { id: 166, name: '生汆丸子汤', emoji: '🍲', price: 0, desc: '生汆丸子汤，吃的就是一个鲜、嫩、弹。', category: '汤类', image: `${IMG.soup}/生汆丸子汤/生汆丸子汤.jpg`, tutorialUrl: `${R}/soup/生汆丸子汤/生汆丸子汤.md` },
  { id: 167, name: '番茄牛肉蛋花汤', emoji: '🍲', price: 0, desc: '预估烹饪难度：★★★', category: '汤类', image: `${IMG.soup}/番茄牛肉蛋花汤/番茄牛肉蛋花汤.jpg`, tutorialUrl: `${R}/soup/番茄牛肉蛋花汤/番茄牛肉蛋花汤.md` },
  { id: 168, name: '米粥', emoji: '🍚', price: 0, desc: '大米粥是一道以大米和水作為主要原料經大火煮沸熬製而成的美食，老少皆宜，米粥具有補脾、和胃、清肺功效。', category: '汤类', image: `${IMG.soup}/米粥/米粥.jpg`, tutorialUrl: `${R}/soup/米粥/米粥.md` },
  { id: 169, name: '羊肉汤', emoji: '🍲', price: 0, desc: '羊肉汤/羊肉汤简单易，有抵御寒冷、温润养胃、开胃健脾的功效，富含钙、铁、蛋白质等营养物质。', category: '汤类', image: `${IMG.soup}/羊肉汤/羊肉汤.jpg`, tutorialUrl: `${R}/soup/羊肉汤/羊肉汤.md` },
  { id: 170, name: '腊八粥', emoji: '🍚', price: 0, desc: '> 无论盛在哪里的腊八粥，自然会熬煮过去。一年的酸甜苦辣涩。—— 迷迭香《腊八粥》', category: '汤类', image: `${IMG.soup}/腊八粥/腊八粥.jpg`, tutorialUrl: `${R}/soup/腊八粥/腊八粥.md` },
  { id: 171, name: '菌菇炖乳鸽', emoji: '🍄', price: 0, desc: '- 菌菇炖乳鸽 汤鲜、肉嫩、营养丰富', category: '汤类', image: `${IMG.soup}/菌菇炖乳鸽/菌菇炖乳鸽.jpg`, tutorialUrl: `${R}/soup/菌菇炖乳鸽/菌菇炖乳鸽.md` },
  { id: 172, name: '金针菇汤', emoji: '🍲', price: 0, desc: '预估烹饪难度：★★', category: '汤类', image: `${IMG.soup}/金针菇汤/金针菇汤.jpg`, tutorialUrl: `${R}/soup/金针菇汤/金针菇汤.md` },
  { id: 173, name: '陈皮排骨汤', emoji: '🍲', price: 0, desc: '新鲜的排骨除了拿来烧或者炖之外，还可以用来煲汤，搭配广东陈皮煲出来的汤非常养生，对脾胃、肺及咽喉都有一定的滋补功效，熬夜', category: '汤类', image: `${IMG.soup}/陈皮排骨汤/陈皮排骨汤.jpg`, tutorialUrl: `${R}/soup/陈皮排骨汤/陈皮排骨汤.md` },
  { id: 174, name: '黄瓜皮蛋汤', emoji: '🍲', price: 0, desc: '黄瓜皮蛋汤是快手的家常汤品，清淡中带着焦香，暖心暖胃又不油腻。简单到厨房小白都能轻松搞定哟！', category: '汤类', image: `${IMG.soup}/黄瓜皮蛋汤/黄瓜皮蛋汤.jpg`, tutorialUrl: `${R}/soup/黄瓜皮蛋汤/黄瓜皮蛋汤.md` },
  
  // ======= 主食（续）=======
  { id: 175, name: '中式馅饼', emoji: '🥞', price: 0, desc: '预估烹饪难度：★★★★', category: '主食', image: `${IMG.staple}/中式馅饼/中式馅饼.jpg`, tutorialUrl: `${R}/staple/中式馅饼/中式馅饼.md` },
  { id: 176, name: '凉粉', emoji: '🍝', price: 0, desc: '伤心凉粉吃了不会让人伤心的哦！', category: '主食', image: `${IMG.staple}/凉粉/凉粉.md`, tutorialUrl: `${R}/staple/凉粉/凉粉.md` },
  { id: 177, name: '利提巧卡', emoji: '🍜', price: 0, desc: '> Litti Chokha(लिट्टी चोखा)— 比哈尔邦烤麦球配蔬菜泥', category: '主食', image: `${IMG.staple}/利提巧卡/利提巧卡.jpg`, tutorialUrl: `${R}/staple/利提巧卡/利提巧卡.md` },
  { id: 178, name: '印度烤饼', emoji: '🥞', price: 0, desc: '> Naan(नान)— 印度发酵烤饼', category: '主食', image: `${IMG.staple}/印度烤饼/印度烤饼.jpg`, tutorialUrl: `${R}/staple/印度烤饼/印度烤饼.md` },
  { id: 179, name: '印度焖饭', emoji: '🍚', price: 0, desc: '> Dum Biryani(दम बिरयानी)— 印度香料焖饭', category: '主食', image: `${IMG.staple}/印度焖饭/印度焖饭.jpg`, tutorialUrl: `${R}/staple/印度焖饭/印度焖饭.md` },
  { id: 180, name: '可乐炒饭', emoji: '🍚', price: 0, desc: '预估烹饪难度：★★', category: '主食', image: `${IMG.staple}/可乐炒饭/可乐炒饭.jpg`, tutorialUrl: `${R}/staple/可乐炒饭/可乐炒饭.md` },
  { id: 181, name: '咸肉菜饭', emoji: '🍚', price: 0, desc: '预估烹饪难度：★★', category: '主食', image: `${IMG.staple}/咸肉菜饭/咸肉菜饭.jpg`, tutorialUrl: `${R}/staple/咸肉菜饭/咸肉菜饭.md` },
  { id: 182, name: '基础牛奶面包', emoji: '🍞', price: 0, desc: '面包的基础配方是烘焙中最常用的配方，通过改变面团中的液体、油脂和糖的数量，可以制造出各种不同的面包', category: '主食', image: `${IMG.staple}/基础牛奶面包/4-6成品面包.jpg`, tutorialUrl: `${R}/staple/基础牛奶面包/基础牛奶面包.md` },
  { id: 183, name: '微波炉腊肠煲仔饭', emoji: '🍚', price: 0, desc: '你家里没有砂锅吗？用微波炉也能做煲仔饭呢，不过就不能煲出那种香喷喷的焦米的感觉。', category: '主食', image: `${IMG.staple}/微波炉腊肠煲仔饭/微波炉腊肠煲仔饭.png`, tutorialUrl: `${R}/staple/微波炉腊肠煲仔饭/微波炉腊肠煲仔饭.md` },
  { id: 184, name: '意式肉酱面', emoji: '🍝', price: 0, desc: '意大利肉酱面是意大利菜，由意大利面和番茄肉酱组成。', category: '主食', image: `${IMG.staple}/意式肉酱面/final.jpg`, tutorialUrl: `${R}/staple/意式肉酱面/意式肉酱面.md` },
  { id: 185, name: '烙饼', emoji: '🫓', price: 0, desc: '烙饼是一种面食，是用面粉和水烧制而成的传统食品', category: '主食', image: `${IMG.staple}/烙饼/成品.jpg`, tutorialUrl: `${R}/staple/烙饼/烙饼.md` },
  { id: 186, name: '烧饼', emoji: '🥞', price: 0, desc: '烧饼是一种常见的中国面食，起源于中国，用面粉制成的，呈圆形。', category: '主食', image: `${IMG.staple}/烧饼/芝麻烧饼.jpg`, tutorialUrl: `${R}/staple/烧饼/芝麻烧饼.md` },
  { id: 187, name: '汤面', emoji: '🍜', price: 0, desc: '预估烹饪难度：★', category: '主食', image: `${IMG.staple}/汤面/汤面.jpg`, tutorialUrl: `${R}/staple/汤面/汤面.md` },
  { id: 188, name: '河南蒸面条', emoji: '🍜', price: 0, desc: '河南蒸面条是一道豫南的非常经典的家常菜，荤素搭档，简单易学。', category: '主食', image: `${IMG.staple}/河南蒸面条/河南蒸面条.png`, tutorialUrl: `${R}/staple/河南蒸面条/河南蒸面条.md` },
  { id: 189, name: '炒凉粉', emoji: '🍝', price: 0, desc: '凉粉炒着吃口感和味道还不错，简单易做。', category: '主食', image: `${IMG.staple}/炒凉粉/炒凉粉成品.jpg`, tutorialUrl: `${R}/staple/炒凉粉/炒凉粉.md` },
  { id: 190, name: '炒年糕', emoji: '🍚', price: 0, desc: '预估烹饪难度：★★', category: '主食', image: `${IMG.staple}/炒年糕/炒年糕.jpg`, tutorialUrl: `${R}/staple/炒年糕/炒年糕.md` },
  { id: 191, name: '炒意大利面', emoji: '🍝', price: 0, desc: '预估烹饪难度：★★', category: '主食', image: `${IMG.staple}/炒意大利面/a.jpg`, tutorialUrl: `${R}/staple/炒意大利面/炒意大利面.md` },
  { id: 192, name: '炒方便面', emoji: '🍜', price: 0, desc: '预估烹饪难度：★', category: '主食', image: `${IMG.staple}/炒方便面/炒方便面.jpg`, tutorialUrl: `${R}/staple/炒方便面/炒方便面.md` },
  { id: 193, name: '炒河粉', emoji: '🍜', price: 0, desc: '预估烹饪难度：★★', category: '主食', image: `${IMG.staple}/炒河粉/炒河粉.jpg`, tutorialUrl: `${R}/staple/炒河粉/炒河粉.md` },
  { id: 194, name: '炒馍', emoji: '🥞', price: 0, desc: '预估烹饪难度：★', category: '主食', image: `${IMG.staple}/炒馍/炒馍.jpg`, tutorialUrl: `${R}/staple/炒馍/炒馍.md` },
  { id: 195, name: '火腿饭团', emoji: '🍙', price: 0, desc: '简单方便的日式便当', category: '主食', image: `${IMG.staple}/火腿饭团/饭团.png`, tutorialUrl: `${R}/staple/火腿饭团/火腿饭团.md` },
  { id: 196, name: '披萨饼皮', emoji: '🍕', price: 0, desc: '这是一份万能的披萨饼皮配方，可以制作出传统披萨风格的脆皮或芝加哥深盘披萨。', category: '主食', image: `${IMG.staple}/披萨饼皮/001.jpeg`, tutorialUrl: `${R}/staple/披萨饼皮/披萨饼皮.md` },
  { id: 197, name: '日式咖喱饭', emoji: '🍚', price: 0, desc: '咖喱饭是比较常见的家常米饭制作方法，咖喱的香味和米饭的软绵结合起来，让整道菜的味觉层次更丰富。', category: '主食', image: `${IMG.staple}/日式咖喱饭/成品.jpg`, tutorialUrl: `${R}/staple/日式咖喱饭/日式咖喱饭.md` },
  { id: 198, name: '日式肥牛丼饭', emoji: '🍚', price: 0, desc: '肥牛丼是一道日式盖饭，采用优质肥牛和洋葱为主要原材料，经过精心烹饪而成。', category: '主食', image: `${IMG.staple}/日式肥牛丼饭/成品.png`, tutorialUrl: `${R}/staple/日式肥牛丼饭/日式肥牛丼饭.md` },
  { id: 199, name: '猪油拌饭', emoji: '🍚', price: 0, desc: '预估烹饪难度：★', category: '主食', image: `${IMG.staple}/猪油拌饭/猪油拌饭.jpg`, tutorialUrl: `${R}/staple/猪油拌饭/猪油拌饭.md` },
  { id: 200, name: '空气炸锅照烧鸡饭', emoji: '🍚', price: 0, desc: '简单快手的空气炸锅做法，烹饪时间仅需 30 分钟。', category: '主食', image: `${IMG.staple}/空气炸锅照烧鸡饭/空气炸锅照烧鸡饭.jpg`, tutorialUrl: `${R}/staple/空气炸锅照烧鸡饭/空气炸锅照烧鸡饭.md` },
  { id: 201, name: '电饭煲三文鱼炊饭', emoji: '🍚', price: 0, desc: '一个人在宿舍也能用电饭煲做出好吃的三文鱼炊饭。', category: '主食', image: `${IMG.staple}/电饭煲三文鱼炊饭/电饭煲三文鱼炊饭.webp`, tutorialUrl: `${R}/staple/电饭煲三文鱼炊饭/电饭煲三文鱼炊饭.md` },
  { id: 202, name: '米饭', emoji: '🍚', price: 0, desc: '煮好米饭是做好任何米饭类菜肴的基础', category: '主食', image: `${IMG.staple}/米饭/rice_regularPot.jpeg`, tutorialUrl: `${R}/staple/米饭/电饭煲蒸米饭.md` },
  { id: 203, name: '红芸豆拌饭', emoji: '🍚', price: 0, desc: '> Rajma Chawal(राजमा चावल)— 红芸豆咖喱配米饭', category: '主食', image: `${IMG.staple}/红芸豆拌饭/红芸豆拌饭.jpg`, tutorialUrl: `${R}/staple/红芸豆拌饭/红芸豆拌饭.md` },
  { id: 204, name: '老友猪肉粉', emoji: '🍝', price: 0, desc: '预估烹饪难度：★★★', category: '主食', image: `${IMG.staple}/老友猪肉粉/老友猪肉粉.jpg`, tutorialUrl: `${R}/staple/老友猪肉粉/老友猪肉粉.md` },
  { id: 205, name: '老干妈拌面', emoji: '🍜', price: 0, desc: '预估烹饪难度：★', category: '主食', image: `${IMG.staple}/老干妈拌面/老干妈拌面.jpg`, tutorialUrl: `${R}/staple/老干妈拌面/老干妈拌面.md` },
  { id: 206, name: '肉蛋盖饭', emoji: '🍚', price: 0, desc: '肉蛋盖饭适合于单人简易晚餐，烹饪大约需要十五分钟。', category: '主食', image: `${IMG.staple}/肉蛋盖饭/肉蛋盖饭.jpg`, tutorialUrl: `${R}/staple/肉蛋盖饭/肉蛋盖饭.md` },
  { id: 207, name: '茄子肉煎饼', emoji: '🥞', price: 0, desc: '茄子肉煎饼是一道简单易做的饼类主食。', category: '主食', image: `${IMG.staple}/茄子肉煎饼/茄子肉煎饼.jpg`, tutorialUrl: `${R}/staple/茄子肉煎饼/茄子肉煎饼.md` },
  { id: 208, name: '蒸卤面', emoji: '🍜', price: 0, desc: '蒸卤面是一道豫南的非常经典的家常菜，荤素搭档，简单易学。一般初学者只需要一个小时即可完成。', category: '主食', image: `${IMG.staple}/蒸卤面/蒸卤面.jpg`, tutorialUrl: `${R}/staple/蒸卤面/蒸卤面.md` },
  { id: 209, name: '西红柿鸡蛋挂面', emoji: '🍜', price: 0, desc: '挂面太多怎么办？只煮个白水面味道难以下咽怎么办？简单的食材煮个美味的面条怎么操作？', category: '主食', image: `${IMG.staple}/西红柿鸡蛋挂面/food.jpg`, tutorialUrl: `${R}/staple/西红柿鸡蛋挂面/西红柿鸡蛋挂面.md` },
  { id: 210, name: '豆角焖面', emoji: '🍜', price: 0, desc: '豆角焖面是一道懒人美食，操作简单，方便美味。', category: '主食', image: `${IMG.staple}/豆角焖面/豆角焖面.jpg`, tutorialUrl: `${R}/staple/豆角焖面/豆角焖面.md` },
  { id: 211, name: '酱拌荞麦面', emoji: '🍜', price: 0, desc: '酱拌荞麦面营养健康、酸甜可口', category: '主食', image: `${IMG.staple}/酱拌荞麦面/酱拌荞麦面.jpg`, tutorialUrl: `${R}/staple/酱拌荞麦面/酱拌荞麦面.md` },
  { id: 212, name: '酸辣蕨根粉', emoji: '🍝', price: 0, desc: '酸辣蕨根粉是一道适合初学者的简单易做的凉菜，可做主食，以酸辣口为主，预计 10 分钟可做完。', category: '主食', image: `${IMG.staple}/酸辣蕨根粉/酸辣蕨根粉.jpg`, tutorialUrl: `${R}/staple/酸辣蕨根粉/酸辣蕨根粉.md` },
  { id: 213, name: '醪糟小汤圆', emoji: '🍜', price: 0, desc: '预估烹饪难度：★★', category: '主食', image: `${IMG.staple}/醪糟小汤圆/醪糟小汤圆.jpg`, tutorialUrl: `${R}/staple/醪糟小汤圆/醪糟小汤圆.md` },
  { id: 214, name: '陕西油泼面', emoji: '🍜', price: 0, desc: '陕西油泼面是中国西北地区极具代表性的传统面食，以面条筋道、香辣开胃著称。其制作过程简单快捷，核心在于最后热油泼洒在调料上', category: '主食', image: `${IMG.staple}/陕西油泼面/成品.png`, tutorialUrl: `${R}/staple/陕西油泼面/陕西油泼面.md` },
  { id: 215, name: '韭菜盒子', emoji: '🍜', price: 0, desc: '韭菜盒子是一道美味的传统小吃，外皮酥脆，内馅鲜香，富含维生素和蛋白质。制作简单，适合午餐，预计制作时长约 2.5 小时。', category: '主食', image: `${IMG.staple}/韭菜盒子/韭菜盒子.jpg`, tutorialUrl: `${R}/staple/韭菜盒子/韭菜盒子.md` },
  { id: 216, name: '鲜肉烧卖', emoji: '🍚', price: 0, desc: '鲜肉烧卖以肥瘦三七的猪肉为主馅，融入冬笋、皮冻与香菇，蒸出半透明皮子与多汁内馅，一口咬下，汤汁四溢，咸鲜交织，尽显江南精', category: '主食', image: `${IMG.staple}/鲜肉烧卖/鲜肉烧卖.jpg`, tutorialUrl: `${R}/staple/鲜肉烧卖/鲜肉烧卖.md` },
  { id: 217, name: '鲣鱼海苔玉米饭', emoji: '🍚', price: 0, desc: '空气炸锅羊排超级懒人版，味道尚可，主要看羊排的品质。', category: '主食', image: `${IMG.staple}/鲣鱼海苔玉米饭/米饭.jpg`, tutorialUrl: `${R}/staple/鲣鱼海苔玉米饭/鲣鱼海苔玉米饭.md` },
  { id: 218, name: '鹰嘴豆炸饼', emoji: '🥞', price: 0, desc: '> Chole Bhature(छोले भटूरे)— 鹰嘴豆咖喱配油炸面饼', category: '主食', image: `${IMG.staple}/鹰嘴豆炸饼/鹰嘴豆炸饼.jpg`, tutorialUrl: `${R}/staple/鹰嘴豆炸饼/鹰嘴豆炸饼.md` },
  { id: 219, name: '麻油拌面', emoji: '🍜', price: 0, desc: '省吃俭用懒人的菜：麻油拌面：想必大家都会有节约开销的时刻吧，附上个人耐吃又省钱的食谱。不需要太多的步骤简单的煮，捞，吃。', category: '主食', image: `${IMG.staple}/麻油拌面/麻油拌面.jpg`, tutorialUrl: `${R}/staple/麻油拌面/麻油拌面.md` },
  { id: 220, name: '麻辣减脂荞麦面', emoji: '🍜', price: 0, desc: '麻辣减脂荞麦面做法非常简单，不需要任何厨艺基础。', category: '主食', image: `${IMG.staple}/麻辣减脂荞麦面/麻辣减脂荞麦面.jpg`, tutorialUrl: `${R}/staple/麻辣减脂荞麦面/麻辣减脂荞麦面.md` }

]

const categoryColors = {
  '早餐': '#FFA94D',
  '肉菜': '#FF6B6B',
  '主食': '#FFD93D',
  '汤类': '#95E1D3',
  '饮品': '#A8D8EA',
  '水产': '#B19CD9',
  '调味料': '#D4A574',
  '甜点': '#F8B195',
  '半成品': '#E8DAEF',
}

module.exports = {
  categories,
  dishes,
  categoryColors,
}
